syntax = "proto3";

package metrics;

option go_package = "github.com/accretional/grpc-server-config/pb/metrics";

import "metrics/aggregation_service.proto";


// Example: fetch gce_instance::compute.googleapis.com/instance/cpu/utilization
//          | align mean(1m)
//          | every 1m
//          | group_by [resource.labels.zone], mean()
//          | within 1h
message QueryRequest {
  string mql_query = 1;
}

message QueryResponse {
  AnyTimeSeries series = 1;
}

service QueryService {
  rpc Query(QueryRequest) returns (stream QueryResponse);
}
