// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: metrics/aggregation_service.proto

package metrics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AggregationService_Align_FullMethodName  = "/metrics.AggregationService/Align"
	AggregationService_Reduce_FullMethodName = "/metrics.AggregationService/Reduce"
)

// AggregationServiceClient is the client API for AggregationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AggregationService implements the two-phase align → reduce pipeline used by
// time series query languages such as MQL.
//
// Typical call sequence:
//  1. Call Align once per input series with the chosen Aligner and period.
//  2. Collect AlignResponse.output series for all inputs of the same type.
//  3. Call Reduce with those aligned series to collapse across label dimensions.
type AggregationServiceClient interface {
	// Align transforms a single time series into fixed-duration aligned buckets.
	// Each output point represents the result of the aligner operation applied to
	// all input points that fall within that alignment period.
	//
	// The output kind may differ from the input kind (see AnyTimeSeries).
	Align(ctx context.Context, in *AlignRequest, opts ...grpc.CallOption) (*AlignResponse, error)
	// Reduce combines multiple already-aligned time series into fewer series by
	// applying a cross-series aggregation, optionally grouped by label fields.
	//
	// All input series must be of the same kind and aligned to the same period.
	// The output series carry only the labels listed in group_by_fields.
	Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceResponse, error)
}

type aggregationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAggregationServiceClient(cc grpc.ClientConnInterface) AggregationServiceClient {
	return &aggregationServiceClient{cc}
}

func (c *aggregationServiceClient) Align(ctx context.Context, in *AlignRequest, opts ...grpc.CallOption) (*AlignResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AlignResponse)
	err := c.cc.Invoke(ctx, AggregationService_Align_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aggregationServiceClient) Reduce(ctx context.Context, in *ReduceRequest, opts ...grpc.CallOption) (*ReduceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReduceResponse)
	err := c.cc.Invoke(ctx, AggregationService_Reduce_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AggregationServiceServer is the server API for AggregationService service.
// All implementations should embed UnimplementedAggregationServiceServer
// for forward compatibility.
//
// AggregationService implements the two-phase align → reduce pipeline used by
// time series query languages such as MQL.
//
// Typical call sequence:
//  1. Call Align once per input series with the chosen Aligner and period.
//  2. Collect AlignResponse.output series for all inputs of the same type.
//  3. Call Reduce with those aligned series to collapse across label dimensions.
type AggregationServiceServer interface {
	// Align transforms a single time series into fixed-duration aligned buckets.
	// Each output point represents the result of the aligner operation applied to
	// all input points that fall within that alignment period.
	//
	// The output kind may differ from the input kind (see AnyTimeSeries).
	Align(context.Context, *AlignRequest) (*AlignResponse, error)
	// Reduce combines multiple already-aligned time series into fewer series by
	// applying a cross-series aggregation, optionally grouped by label fields.
	//
	// All input series must be of the same kind and aligned to the same period.
	// The output series carry only the labels listed in group_by_fields.
	Reduce(context.Context, *ReduceRequest) (*ReduceResponse, error)
}

// UnimplementedAggregationServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAggregationServiceServer struct{}

func (UnimplementedAggregationServiceServer) Align(context.Context, *AlignRequest) (*AlignResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Align not implemented")
}
func (UnimplementedAggregationServiceServer) Reduce(context.Context, *ReduceRequest) (*ReduceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reduce not implemented")
}
func (UnimplementedAggregationServiceServer) testEmbeddedByValue() {}

// UnsafeAggregationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AggregationServiceServer will
// result in compilation errors.
type UnsafeAggregationServiceServer interface {
	mustEmbedUnimplementedAggregationServiceServer()
}

func RegisterAggregationServiceServer(s grpc.ServiceRegistrar, srv AggregationServiceServer) {
	// If the following call panics, it indicates UnimplementedAggregationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AggregationService_ServiceDesc, srv)
}

func _AggregationService_Align_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AlignRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).Align(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_Align_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).Align(ctx, req.(*AlignRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AggregationService_Reduce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReduceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AggregationServiceServer).Reduce(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AggregationService_Reduce_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AggregationServiceServer).Reduce(ctx, req.(*ReduceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AggregationService_ServiceDesc is the grpc.ServiceDesc for AggregationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AggregationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.AggregationService",
	HandlerType: (*AggregationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Align",
			Handler:    _AggregationService_Align_Handler,
		},
		{
			MethodName: "Reduce",
			Handler:    _AggregationService_Reduce_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "metrics/aggregation_service.proto",
}
