// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/aggregation.proto

package metrics

import (
	pb "github.com/accretional/gluon/v2/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Aligner describes the per-series operation applied within each alignment
// period. The operation collapses all data points in a period into a single
// output point placed at the period's end boundary.
//
// Field numbers match google.monitoring.v3 for easy cross-referencing.
type Aligner int32

const (
	// No alignment. Raw data is returned as-is. Cross-series reduction
	// (via Aggregation.aligned) is not permitted with this aligner.
	Aligner_ALIGN_NONE Aligner = 0
	// Convert CUMULATIVE to DELTA: output[i] = cumulative[i] - cumulative[i-1].
	// Valid for CUMULATIVE input. Output is DeltaTimeSeries.
	Aligner_ALIGN_DELTA Aligner = 1
	// Convert CUMULATIVE or DELTA to a per-second rate: delta_value / duration.
	// Output is GaugeTimeSeries with DOUBLE values.
	Aligner_ALIGN_RATE Aligner = 2
	// Interpolate GAUGE values at alignment period boundaries using linear
	// interpolation between adjacent points. Valid for GAUGE numeric.
	Aligner_ALIGN_INTERPOLATE Aligner = 3
	// Carry forward the most recent GAUGE value before each period end to the
	// period boundary. Valid for GAUGE.
	Aligner_ALIGN_NEXT_OLDER Aligner = 4
	// Minimum value in each alignment period. Valid for GAUGE and DELTA numeric.
	Aligner_ALIGN_MIN Aligner = 10
	// Maximum value in each alignment period. Valid for GAUGE and DELTA numeric.
	Aligner_ALIGN_MAX Aligner = 11
	// Mean of values in each alignment period. Output is DOUBLE.
	// Valid for GAUGE and DELTA numeric.
	Aligner_ALIGN_MEAN Aligner = 12
	// Count of data points in each alignment period. Output is INT64.
	// Valid for GAUGE and DELTA numeric or boolean.
	Aligner_ALIGN_COUNT Aligner = 13
	// Sum of values in each alignment period.
	// Valid for GAUGE and DELTA numeric and distribution.
	Aligner_ALIGN_SUM Aligner = 14
	// Standard deviation of values in each alignment period. Output is DOUBLE.
	// Valid for GAUGE and DELTA numeric.
	Aligner_ALIGN_STDDEV Aligner = 15
	// Count of True values in each alignment period. Output is INT64.
	// Valid for GAUGE BOOL.
	Aligner_ALIGN_COUNT_TRUE Aligner = 16
	// Count of False values in each alignment period. Output is INT64.
	// Valid for GAUGE BOOL.
	Aligner_ALIGN_COUNT_FALSE Aligner = 24
	// Ratio of True values to total values in each alignment period [0.0, 1.0].
	// Output is DOUBLE. Valid for GAUGE BOOL.
	Aligner_ALIGN_FRACTION_TRUE Aligner = 17
	// 99th percentile of DISTRIBUTION values in each alignment period.
	// Output is GAUGE DOUBLE. Valid for GAUGE and DELTA DISTRIBUTION.
	Aligner_ALIGN_PERCENTILE_99 Aligner = 18
	// 95th percentile. See ALIGN_PERCENTILE_99.
	Aligner_ALIGN_PERCENTILE_95 Aligner = 19
	// 50th percentile (median). See ALIGN_PERCENTILE_99.
	Aligner_ALIGN_PERCENTILE_50 Aligner = 20
	// 5th percentile. See ALIGN_PERCENTILE_99.
	Aligner_ALIGN_PERCENTILE_05 Aligner = 21
	// Percentage change relative to the previous alignment period:
	//
	//	((current - previous) / previous) * 100
	//
	// A 10-minute moving mean is applied to each period before this calculation
	// to reduce noise from short-lived spikes. Output is GAUGE DOUBLE.
	// Valid for GAUGE and DELTA numeric.
	Aligner_ALIGN_PERCENT_CHANGE Aligner = 23
)

// Enum value maps for Aligner.
var (
	Aligner_name = map[int32]string{
		0:  "ALIGN_NONE",
		1:  "ALIGN_DELTA",
		2:  "ALIGN_RATE",
		3:  "ALIGN_INTERPOLATE",
		4:  "ALIGN_NEXT_OLDER",
		10: "ALIGN_MIN",
		11: "ALIGN_MAX",
		12: "ALIGN_MEAN",
		13: "ALIGN_COUNT",
		14: "ALIGN_SUM",
		15: "ALIGN_STDDEV",
		16: "ALIGN_COUNT_TRUE",
		24: "ALIGN_COUNT_FALSE",
		17: "ALIGN_FRACTION_TRUE",
		18: "ALIGN_PERCENTILE_99",
		19: "ALIGN_PERCENTILE_95",
		20: "ALIGN_PERCENTILE_50",
		21: "ALIGN_PERCENTILE_05",
		23: "ALIGN_PERCENT_CHANGE",
	}
	Aligner_value = map[string]int32{
		"ALIGN_NONE":           0,
		"ALIGN_DELTA":          1,
		"ALIGN_RATE":           2,
		"ALIGN_INTERPOLATE":    3,
		"ALIGN_NEXT_OLDER":     4,
		"ALIGN_MIN":            10,
		"ALIGN_MAX":            11,
		"ALIGN_MEAN":           12,
		"ALIGN_COUNT":          13,
		"ALIGN_SUM":            14,
		"ALIGN_STDDEV":         15,
		"ALIGN_COUNT_TRUE":     16,
		"ALIGN_COUNT_FALSE":    24,
		"ALIGN_FRACTION_TRUE":  17,
		"ALIGN_PERCENTILE_99":  18,
		"ALIGN_PERCENTILE_95":  19,
		"ALIGN_PERCENTILE_50":  20,
		"ALIGN_PERCENTILE_05":  21,
		"ALIGN_PERCENT_CHANGE": 23,
	}
)

func (x Aligner) Enum() *Aligner {
	p := new(Aligner)
	*p = x
	return p
}

func (x Aligner) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Aligner) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_aggregation_proto_enumTypes[0].Descriptor()
}

func (Aligner) Type() protoreflect.EnumType {
	return &file_metrics_aggregation_proto_enumTypes[0]
}

func (x Aligner) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Aligner.Descriptor instead.
func (Aligner) EnumDescriptor() ([]byte, []int) {
	return file_metrics_aggregation_proto_rawDescGZIP(), []int{0}
}

// Reducer describes how to combine multiple already-aligned time series into
// fewer series. Reduction happens after alignment.
//
// Field numbers match google.monitoring.v3 for easy cross-referencing.
type Reducer int32

const (
	// No cross-series reduction. Aligned series are returned as-is.
	Reducer_REDUCE_NONE Reducer = 0
	// Mean across series at each aligned time point. Output is DOUBLE.
	// Valid for DELTA and GAUGE numeric or distribution.
	Reducer_REDUCE_MEAN Reducer = 1
	// Minimum across series at each aligned time point.
	// Valid for DELTA and GAUGE numeric.
	Reducer_REDUCE_MIN Reducer = 2
	// Maximum across series at each aligned time point.
	// Valid for DELTA and GAUGE numeric.
	Reducer_REDUCE_MAX Reducer = 3
	// Sum across series at each aligned time point.
	// Valid for DELTA and GAUGE numeric and distribution.
	Reducer_REDUCE_SUM Reducer = 4
	// Standard deviation across series at each aligned time point. Output is DOUBLE.
	// Valid for DELTA and GAUGE numeric or distribution.
	Reducer_REDUCE_STDDEV Reducer = 5
	// Count of data points across series at each aligned time point. Output is INT64.
	// Valid for DELTA and GAUGE of any value type.
	Reducer_REDUCE_COUNT Reducer = 6
	// Count of True values across series. Output is INT64.
	// Valid for DELTA and GAUGE BOOL.
	Reducer_REDUCE_COUNT_TRUE Reducer = 7
	// Count of False values across series. Output is INT64.
	// Valid for DELTA and GAUGE BOOL.
	Reducer_REDUCE_COUNT_FALSE Reducer = 15
	// Ratio of True to total values across series [0.0, 1.0]. Output is DOUBLE.
	// Valid for DELTA and GAUGE BOOL.
	Reducer_REDUCE_FRACTION_TRUE Reducer = 8
	// 99th percentile across distribution series at each aligned time point.
	// Output is DOUBLE. Valid for GAUGE and DELTA DISTRIBUTION.
	Reducer_REDUCE_PERCENTILE_99 Reducer = 9
	// 95th percentile. See REDUCE_PERCENTILE_99.
	Reducer_REDUCE_PERCENTILE_95 Reducer = 10
	// 50th percentile (median). See REDUCE_PERCENTILE_99.
	Reducer_REDUCE_PERCENTILE_50 Reducer = 11
	// 5th percentile. See REDUCE_PERCENTILE_99.
	Reducer_REDUCE_PERCENTILE_05 Reducer = 12
)

// Enum value maps for Reducer.
var (
	Reducer_name = map[int32]string{
		0:  "REDUCE_NONE",
		1:  "REDUCE_MEAN",
		2:  "REDUCE_MIN",
		3:  "REDUCE_MAX",
		4:  "REDUCE_SUM",
		5:  "REDUCE_STDDEV",
		6:  "REDUCE_COUNT",
		7:  "REDUCE_COUNT_TRUE",
		15: "REDUCE_COUNT_FALSE",
		8:  "REDUCE_FRACTION_TRUE",
		9:  "REDUCE_PERCENTILE_99",
		10: "REDUCE_PERCENTILE_95",
		11: "REDUCE_PERCENTILE_50",
		12: "REDUCE_PERCENTILE_05",
	}
	Reducer_value = map[string]int32{
		"REDUCE_NONE":          0,
		"REDUCE_MEAN":          1,
		"REDUCE_MIN":           2,
		"REDUCE_MAX":           3,
		"REDUCE_SUM":           4,
		"REDUCE_STDDEV":        5,
		"REDUCE_COUNT":         6,
		"REDUCE_COUNT_TRUE":    7,
		"REDUCE_COUNT_FALSE":   15,
		"REDUCE_FRACTION_TRUE": 8,
		"REDUCE_PERCENTILE_99": 9,
		"REDUCE_PERCENTILE_95": 10,
		"REDUCE_PERCENTILE_50": 11,
		"REDUCE_PERCENTILE_05": 12,
	}
)

func (x Reducer) Enum() *Reducer {
	p := new(Reducer)
	*p = x
	return p
}

func (x Reducer) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Reducer) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_aggregation_proto_enumTypes[1].Descriptor()
}

func (Reducer) Type() protoreflect.EnumType {
	return &file_metrics_aggregation_proto_enumTypes[1]
}

func (x Reducer) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Reducer.Descriptor instead.
func (Reducer) EnumDescriptor() ([]byte, []int) {
	return file_metrics_aggregation_proto_rawDescGZIP(), []int{1}
}

// AlignedAggregation pairs a required per-series aligner with an optional
// cross-series reducer. The aligner must not be ALIGN_NONE.
type AlignedAggregation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required. The operation to apply within each alignment period.
	// Must not be ALIGN_NONE (use Aggregation.no_alignment for that case).
	PerSeriesAligner Aligner `protobuf:"varint,1,opt,name=per_series_aligner,json=perSeriesAligner,proto3,enum=metrics.Aligner" json:"per_series_aligner,omitempty"`
	// Optional. The operation to combine series after alignment.
	// REDUCE_NONE means no cross-series reduction; aligned series are returned
	// individually.
	CrossSeriesReducer Reducer `protobuf:"varint,2,opt,name=cross_series_reducer,json=crossSeriesReducer,proto3,enum=metrics.Reducer" json:"cross_series_reducer,omitempty"`
	// Label keys to preserve in the output. Series are grouped by the values
	// of these labels before the reducer is applied; all other label dimensions
	// are aggregated away. Ignored when cross_series_reducer is REDUCE_NONE.
	GroupByFields []string `protobuf:"bytes,3,rep,name=group_by_fields,json=groupByFields,proto3" json:"group_by_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignedAggregation) Reset() {
	*x = AlignedAggregation{}
	mi := &file_metrics_aggregation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignedAggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignedAggregation) ProtoMessage() {}

func (x *AlignedAggregation) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignedAggregation.ProtoReflect.Descriptor instead.
func (*AlignedAggregation) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_proto_rawDescGZIP(), []int{0}
}

func (x *AlignedAggregation) GetPerSeriesAligner() Aligner {
	if x != nil {
		return x.PerSeriesAligner
	}
	return Aligner_ALIGN_NONE
}

func (x *AlignedAggregation) GetCrossSeriesReducer() Reducer {
	if x != nil {
		return x.CrossSeriesReducer
	}
	return Reducer_REDUCE_NONE
}

func (x *AlignedAggregation) GetGroupByFields() []string {
	if x != nil {
		return x.GroupByFields
	}
	return nil
}

// Aggregation describes how to align and optionally reduce one or more time
// series. The oneof on strategy makes it structurally impossible to specify a
// cross-series reducer without also providing an aligner — a constraint that
// Google's Aggregation message only enforces via documentation.
type Aggregation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Required when strategy is aligned. The width of each alignment bucket.
	// Minimum meaningful value is 60s.
	AlignmentPeriod *durationpb.Duration `protobuf:"bytes,1,opt,name=alignment_period,json=alignmentPeriod,proto3" json:"alignment_period,omitempty"`
	// Types that are valid to be assigned to Strategy:
	//
	//	*Aggregation_NoAlignment
	//	*Aggregation_Aligned
	Strategy      isAggregation_Strategy `protobuf_oneof:"strategy"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Aggregation) Reset() {
	*x = Aggregation{}
	mi := &file_metrics_aggregation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Aggregation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Aggregation) ProtoMessage() {}

func (x *Aggregation) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Aggregation.ProtoReflect.Descriptor instead.
func (*Aggregation) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_proto_rawDescGZIP(), []int{1}
}

func (x *Aggregation) GetAlignmentPeriod() *durationpb.Duration {
	if x != nil {
		return x.AlignmentPeriod
	}
	return nil
}

func (x *Aggregation) GetStrategy() isAggregation_Strategy {
	if x != nil {
		return x.Strategy
	}
	return nil
}

func (x *Aggregation) GetNoAlignment() bool {
	if x != nil {
		if x, ok := x.Strategy.(*Aggregation_NoAlignment); ok {
			return x.NoAlignment
		}
	}
	return false
}

func (x *Aggregation) GetAligned() *AlignedAggregation {
	if x != nil {
		if x, ok := x.Strategy.(*Aggregation_Aligned); ok {
			return x.Aligned
		}
	}
	return nil
}

type isAggregation_Strategy interface {
	isAggregation_Strategy()
}

type Aggregation_NoAlignment struct {
	// No alignment or reduction. Raw series are returned as-is.
	// ALIGN_NONE is implied; cross-series reduction is not available here.
	NoAlignment bool `protobuf:"varint,2,opt,name=no_alignment,json=noAlignment,proto3,oneof"`
}

type Aggregation_Aligned struct {
	// Aligned (and optionally reduced) aggregation.
	Aligned *AlignedAggregation `protobuf:"bytes,3,opt,name=aligned,proto3,oneof"`
}

func (*Aggregation_NoAlignment) isAggregation_Strategy() {}

func (*Aggregation_Aligned) isAggregation_Strategy() {}

// QueryError reports a problem encountered while parsing or evaluating a query.
type QueryError struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The text snippet that caused the error, carried as a TextDescriptor so the
	// caller can choose the most efficient encoding (ASCII chunk, unicode run, or
	// raw string). For most query errors, set the unicode_string arm.
	//
	// Note: if a positional reference into the original query string is preferred
	// over embedding the snippet (e.g. line/column/byte offset), replace this
	// field with a text.SourceLocation from text/source_location.proto instead.
	Snippet *pb.TextDescriptor `protobuf:"bytes,1,opt,name=snippet,proto3" json:"snippet,omitempty"`
	// Human-readable explanation of what went wrong and how to fix it.
	Message       string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryError) Reset() {
	*x = QueryError{}
	mi := &file_metrics_aggregation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryError) ProtoMessage() {}

func (x *QueryError) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryError.ProtoReflect.Descriptor instead.
func (*QueryError) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_proto_rawDescGZIP(), []int{2}
}

func (x *QueryError) GetSnippet() *pb.TextDescriptor {
	if x != nil {
		return x.Snippet
	}
	return nil
}

func (x *QueryError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_metrics_aggregation_proto protoreflect.FileDescriptor

const file_metrics_aggregation_proto_rawDesc = "" +
	"\n" +
	"\x19metrics/aggregation.proto\x12\ametrics\x1a\x1egoogle/protobuf/duration.proto\x1a\rv2/text.proto\"\xc0\x01\n" +
	"\x12AlignedAggregation\x12>\n" +
	"\x12per_series_aligner\x18\x01 \x01(\x0e2\x10.metrics.AlignerR\x10perSeriesAligner\x12B\n" +
	"\x14cross_series_reducer\x18\x02 \x01(\x0e2\x10.metrics.ReducerR\x12crossSeriesReducer\x12&\n" +
	"\x0fgroup_by_fields\x18\x03 \x03(\tR\rgroupByFields\"\xbd\x01\n" +
	"\vAggregation\x12D\n" +
	"\x10alignment_period\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x0falignmentPeriod\x12#\n" +
	"\fno_alignment\x18\x02 \x01(\bH\x00R\vnoAlignment\x127\n" +
	"\aaligned\x18\x03 \x01(\v2\x1b.metrics.AlignedAggregationH\x00R\aalignedB\n" +
	"\n" +
	"\bstrategy\"Z\n" +
	"\n" +
	"QueryError\x122\n" +
	"\asnippet\x18\x01 \x01(\v2\x18.gluon.v2.TextDescriptorR\asnippet\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage*\x8b\x03\n" +
	"\aAligner\x12\x0e\n" +
	"\n" +
	"ALIGN_NONE\x10\x00\x12\x0f\n" +
	"\vALIGN_DELTA\x10\x01\x12\x0e\n" +
	"\n" +
	"ALIGN_RATE\x10\x02\x12\x15\n" +
	"\x11ALIGN_INTERPOLATE\x10\x03\x12\x14\n" +
	"\x10ALIGN_NEXT_OLDER\x10\x04\x12\r\n" +
	"\tALIGN_MIN\x10\n" +
	"\x12\r\n" +
	"\tALIGN_MAX\x10\v\x12\x0e\n" +
	"\n" +
	"ALIGN_MEAN\x10\f\x12\x0f\n" +
	"\vALIGN_COUNT\x10\r\x12\r\n" +
	"\tALIGN_SUM\x10\x0e\x12\x10\n" +
	"\fALIGN_STDDEV\x10\x0f\x12\x14\n" +
	"\x10ALIGN_COUNT_TRUE\x10\x10\x12\x15\n" +
	"\x11ALIGN_COUNT_FALSE\x10\x18\x12\x17\n" +
	"\x13ALIGN_FRACTION_TRUE\x10\x11\x12\x17\n" +
	"\x13ALIGN_PERCENTILE_99\x10\x12\x12\x17\n" +
	"\x13ALIGN_PERCENTILE_95\x10\x13\x12\x17\n" +
	"\x13ALIGN_PERCENTILE_50\x10\x14\x12\x17\n" +
	"\x13ALIGN_PERCENTILE_05\x10\x15\x12\x18\n" +
	"\x14ALIGN_PERCENT_CHANGE\x10\x17*\xb1\x02\n" +
	"\aReducer\x12\x0f\n" +
	"\vREDUCE_NONE\x10\x00\x12\x0f\n" +
	"\vREDUCE_MEAN\x10\x01\x12\x0e\n" +
	"\n" +
	"REDUCE_MIN\x10\x02\x12\x0e\n" +
	"\n" +
	"REDUCE_MAX\x10\x03\x12\x0e\n" +
	"\n" +
	"REDUCE_SUM\x10\x04\x12\x11\n" +
	"\rREDUCE_STDDEV\x10\x05\x12\x10\n" +
	"\fREDUCE_COUNT\x10\x06\x12\x15\n" +
	"\x11REDUCE_COUNT_TRUE\x10\a\x12\x16\n" +
	"\x12REDUCE_COUNT_FALSE\x10\x0f\x12\x18\n" +
	"\x14REDUCE_FRACTION_TRUE\x10\b\x12\x18\n" +
	"\x14REDUCE_PERCENTILE_99\x10\t\x12\x18\n" +
	"\x14REDUCE_PERCENTILE_95\x10\n" +
	"\x12\x18\n" +
	"\x14REDUCE_PERCENTILE_50\x10\v\x12\x18\n" +
	"\x14REDUCE_PERCENTILE_05\x10\fB6Z4github.com/accretional/grpc-server-config/pb/metricsb\x06proto3"

var (
	file_metrics_aggregation_proto_rawDescOnce sync.Once
	file_metrics_aggregation_proto_rawDescData []byte
)

func file_metrics_aggregation_proto_rawDescGZIP() []byte {
	file_metrics_aggregation_proto_rawDescOnce.Do(func() {
		file_metrics_aggregation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_aggregation_proto_rawDesc), len(file_metrics_aggregation_proto_rawDesc)))
	})
	return file_metrics_aggregation_proto_rawDescData
}

var file_metrics_aggregation_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metrics_aggregation_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_metrics_aggregation_proto_goTypes = []any{
	(Aligner)(0),                // 0: metrics.Aligner
	(Reducer)(0),                // 1: metrics.Reducer
	(*AlignedAggregation)(nil),  // 2: metrics.AlignedAggregation
	(*Aggregation)(nil),         // 3: metrics.Aggregation
	(*QueryError)(nil),          // 4: metrics.QueryError
	(*durationpb.Duration)(nil), // 5: google.protobuf.Duration
	(*pb.TextDescriptor)(nil),   // 6: gluon.v2.TextDescriptor
}
var file_metrics_aggregation_proto_depIdxs = []int32{
	0, // 0: metrics.AlignedAggregation.per_series_aligner:type_name -> metrics.Aligner
	1, // 1: metrics.AlignedAggregation.cross_series_reducer:type_name -> metrics.Reducer
	5, // 2: metrics.Aggregation.alignment_period:type_name -> google.protobuf.Duration
	2, // 3: metrics.Aggregation.aligned:type_name -> metrics.AlignedAggregation
	6, // 4: metrics.QueryError.snippet:type_name -> gluon.v2.TextDescriptor
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_metrics_aggregation_proto_init() }
func file_metrics_aggregation_proto_init() {
	if File_metrics_aggregation_proto != nil {
		return
	}
	file_metrics_aggregation_proto_msgTypes[1].OneofWrappers = []any{
		(*Aggregation_NoAlignment)(nil),
		(*Aggregation_Aligned)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_aggregation_proto_rawDesc), len(file_metrics_aggregation_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_aggregation_proto_goTypes,
		DependencyIndexes: file_metrics_aggregation_proto_depIdxs,
		EnumInfos:         file_metrics_aggregation_proto_enumTypes,
		MessageInfos:      file_metrics_aggregation_proto_msgTypes,
	}.Build()
	File_metrics_aggregation_proto = out.File
	file_metrics_aggregation_proto_goTypes = nil
	file_metrics_aggregation_proto_depIdxs = nil
}
