// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: metrics/metric_service.proto

package metrics

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MetricService_WriteTimeSeries_FullMethodName = "/metrics.MetricService/WriteTimeSeries"
)

// MetricServiceClient is the client API for MetricService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MetricService is the ingest endpoint for agents running on monitored hosts.
// Agents open a client-streaming RPC, send one or more batches of time series,
// then close the stream to receive the final written-point count.
type MetricServiceClient interface {
	WriteTimeSeries(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteTimeSeriesRequest, WriteTimeSeriesResponse], error)
}

type metricServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMetricServiceClient(cc grpc.ClientConnInterface) MetricServiceClient {
	return &metricServiceClient{cc}
}

func (c *metricServiceClient) WriteTimeSeries(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[WriteTimeSeriesRequest, WriteTimeSeriesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MetricService_ServiceDesc.Streams[0], MetricService_WriteTimeSeries_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WriteTimeSeriesRequest, WriteTimeSeriesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricService_WriteTimeSeriesClient = grpc.ClientStreamingClient[WriteTimeSeriesRequest, WriteTimeSeriesResponse]

// MetricServiceServer is the server API for MetricService service.
// All implementations should embed UnimplementedMetricServiceServer
// for forward compatibility.
//
// MetricService is the ingest endpoint for agents running on monitored hosts.
// Agents open a client-streaming RPC, send one or more batches of time series,
// then close the stream to receive the final written-point count.
type MetricServiceServer interface {
	WriteTimeSeries(grpc.ClientStreamingServer[WriteTimeSeriesRequest, WriteTimeSeriesResponse]) error
}

// UnimplementedMetricServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMetricServiceServer struct{}

func (UnimplementedMetricServiceServer) WriteTimeSeries(grpc.ClientStreamingServer[WriteTimeSeriesRequest, WriteTimeSeriesResponse]) error {
	return status.Error(codes.Unimplemented, "method WriteTimeSeries not implemented")
}
func (UnimplementedMetricServiceServer) testEmbeddedByValue() {}

// UnsafeMetricServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MetricServiceServer will
// result in compilation errors.
type UnsafeMetricServiceServer interface {
	mustEmbedUnimplementedMetricServiceServer()
}

func RegisterMetricServiceServer(s grpc.ServiceRegistrar, srv MetricServiceServer) {
	// If the following call panics, it indicates UnimplementedMetricServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MetricService_ServiceDesc, srv)
}

func _MetricService_WriteTimeSeries_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricServiceServer).WriteTimeSeries(&grpc.GenericServerStream[WriteTimeSeriesRequest, WriteTimeSeriesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MetricService_WriteTimeSeriesServer = grpc.ClientStreamingServer[WriteTimeSeriesRequest, WriteTimeSeriesResponse]

// MetricService_ServiceDesc is the grpc.ServiceDesc for MetricService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MetricService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "metrics.MetricService",
	HandlerType: (*MetricServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WriteTimeSeries",
			Handler:       _MetricService_WriteTimeSeries_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "metrics/metric_service.proto",
}
