// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/metric_service.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// WriteTimeSeriesRequest carries a batch of time series pushed by an agent.
type WriteTimeSeriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        []*AnyTimeSeries       `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTimeSeriesRequest) Reset() {
	*x = WriteTimeSeriesRequest{}
	mi := &file_metrics_metric_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTimeSeriesRequest) ProtoMessage() {}

func (x *WriteTimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*WriteTimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_metrics_metric_service_proto_rawDescGZIP(), []int{0}
}

func (x *WriteTimeSeriesRequest) GetSeries() []*AnyTimeSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

type WriteTimeSeriesResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of individual data points accepted across all streamed batches.
	PointsWritten int32 `protobuf:"varint,1,opt,name=points_written,json=pointsWritten,proto3" json:"points_written,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteTimeSeriesResponse) Reset() {
	*x = WriteTimeSeriesResponse{}
	mi := &file_metrics_metric_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteTimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteTimeSeriesResponse) ProtoMessage() {}

func (x *WriteTimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteTimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*WriteTimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_metrics_metric_service_proto_rawDescGZIP(), []int{1}
}

func (x *WriteTimeSeriesResponse) GetPointsWritten() int32 {
	if x != nil {
		return x.PointsWritten
	}
	return 0
}

var File_metrics_metric_service_proto protoreflect.FileDescriptor

const file_metrics_metric_service_proto_rawDesc = "" +
	"\n" +
	"\x1cmetrics/metric_service.proto\x12\ametrics\x1a!metrics/aggregation_service.proto\"H\n" +
	"\x16WriteTimeSeriesRequest\x12.\n" +
	"\x06series\x18\x01 \x03(\v2\x16.metrics.AnyTimeSeriesR\x06series\"@\n" +
	"\x17WriteTimeSeriesResponse\x12%\n" +
	"\x0epoints_written\x18\x01 \x01(\x05R\rpointsWritten2g\n" +
	"\rMetricService\x12V\n" +
	"\x0fWriteTimeSeries\x12\x1f.metrics.WriteTimeSeriesRequest\x1a .metrics.WriteTimeSeriesResponse(\x01B6Z4github.com/accretional/grpc-server-config/pb/metricsb\x06proto3"

var (
	file_metrics_metric_service_proto_rawDescOnce sync.Once
	file_metrics_metric_service_proto_rawDescData []byte
)

func file_metrics_metric_service_proto_rawDescGZIP() []byte {
	file_metrics_metric_service_proto_rawDescOnce.Do(func() {
		file_metrics_metric_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_metric_service_proto_rawDesc), len(file_metrics_metric_service_proto_rawDesc)))
	})
	return file_metrics_metric_service_proto_rawDescData
}

var file_metrics_metric_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_metric_service_proto_goTypes = []any{
	(*WriteTimeSeriesRequest)(nil),  // 0: metrics.WriteTimeSeriesRequest
	(*WriteTimeSeriesResponse)(nil), // 1: metrics.WriteTimeSeriesResponse
	(*AnyTimeSeries)(nil),           // 2: metrics.AnyTimeSeries
}
var file_metrics_metric_service_proto_depIdxs = []int32{
	2, // 0: metrics.WriteTimeSeriesRequest.series:type_name -> metrics.AnyTimeSeries
	0, // 1: metrics.MetricService.WriteTimeSeries:input_type -> metrics.WriteTimeSeriesRequest
	1, // 2: metrics.MetricService.WriteTimeSeries:output_type -> metrics.WriteTimeSeriesResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metrics_metric_service_proto_init() }
func file_metrics_metric_service_proto_init() {
	if File_metrics_metric_service_proto != nil {
		return
	}
	file_metrics_aggregation_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_metric_service_proto_rawDesc), len(file_metrics_metric_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_metric_service_proto_goTypes,
		DependencyIndexes: file_metrics_metric_service_proto_depIdxs,
		MessageInfos:      file_metrics_metric_service_proto_msgTypes,
	}.Build()
	File_metrics_metric_service_proto = out.File
	file_metrics_metric_service_proto_goTypes = nil
	file_metrics_metric_service_proto_depIdxs = nil
}
