// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/mql.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ComparisonOp int32

const (
	ComparisonOp_EQ  ComparisonOp = 0 // =   exact match
	ComparisonOp_NEQ ComparisonOp = 1 // !=  not equal
	ComparisonOp_RE  ComparisonOp = 2 // =~  regex match
	ComparisonOp_NRE ComparisonOp = 3 // !~  regex no-match
	ComparisonOp_LT  ComparisonOp = 4 // <
	ComparisonOp_LTE ComparisonOp = 5 // <=
	ComparisonOp_GT  ComparisonOp = 6 // >
	ComparisonOp_GTE ComparisonOp = 7 // >=
)

// Enum value maps for ComparisonOp.
var (
	ComparisonOp_name = map[int32]string{
		0: "EQ",
		1: "NEQ",
		2: "RE",
		3: "NRE",
		4: "LT",
		5: "LTE",
		6: "GT",
		7: "GTE",
	}
	ComparisonOp_value = map[string]int32{
		"EQ":  0,
		"NEQ": 1,
		"RE":  2,
		"NRE": 3,
		"LT":  4,
		"LTE": 5,
		"GT":  6,
		"GTE": 7,
	}
)

func (x ComparisonOp) Enum() *ComparisonOp {
	p := new(ComparisonOp)
	*p = x
	return p
}

func (x ComparisonOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ComparisonOp) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_mql_proto_enumTypes[0].Descriptor()
}

func (ComparisonOp) Type() protoreflect.EnumType {
	return &file_metrics_mql_proto_enumTypes[0]
}

func (x ComparisonOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ComparisonOp.Descriptor instead.
func (ComparisonOp) EnumDescriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{0}
}

type LogicalOp int32

const (
	LogicalOp_AND LogicalOp = 0
	LogicalOp_OR  LogicalOp = 1
)

// Enum value maps for LogicalOp.
var (
	LogicalOp_name = map[int32]string{
		0: "AND",
		1: "OR",
	}
	LogicalOp_value = map[string]int32{
		"AND": 0,
		"OR":  1,
	}
)

func (x LogicalOp) Enum() *LogicalOp {
	p := new(LogicalOp)
	*p = x
	return p
}

func (x LogicalOp) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogicalOp) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_mql_proto_enumTypes[1].Descriptor()
}

func (LogicalOp) Type() protoreflect.EnumType {
	return &file_metrics_mql_proto_enumTypes[1]
}

func (x LogicalOp) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogicalOp.Descriptor instead.
func (LogicalOp) EnumDescriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{1}
}

// QueryPlan is the typed intermediate representation of a parsed MQL query.
// An MQL string → Parse → QueryPlan → Execute → time series.
//
// A plan corresponds to one MQL pipe chain:
//
//	fetch <resource>::<metric>
//	| filter <predicate>
//	| align <aligner>(<period>)
//	| every <period>
//	| group_by [<labels>], <reducer>()
//	| within <duration>
type QueryPlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fetch         *FetchOp               `protobuf:"bytes,1,opt,name=fetch,proto3" json:"fetch,omitempty"`
	Pipeline      []*PipeOp              `protobuf:"bytes,2,rep,name=pipeline,proto3" json:"pipeline,omitempty"`
	TimeRange     *TimeRange             `protobuf:"bytes,3,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryPlan) Reset() {
	*x = QueryPlan{}
	mi := &file_metrics_mql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryPlan) ProtoMessage() {}

func (x *QueryPlan) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryPlan.ProtoReflect.Descriptor instead.
func (*QueryPlan) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{0}
}

func (x *QueryPlan) GetFetch() *FetchOp {
	if x != nil {
		return x.Fetch
	}
	return nil
}

func (x *QueryPlan) GetPipeline() []*PipeOp {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *QueryPlan) GetTimeRange() *TimeRange {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

// FetchOp selects the initial set of time series.
// Maps to: fetch <resource_type>::<metric_type>
type FetchOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monitored resource type, e.g. "gce_instance", "k8s_container".
	ResourceType string `protobuf:"bytes,1,opt,name=resource_type,json=resourceType,proto3" json:"resource_type,omitempty"`
	// Metric type, e.g. "compute.googleapis.com/instance/cpu/utilization".
	MetricType    string `protobuf:"bytes,2,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchOp) Reset() {
	*x = FetchOp{}
	mi := &file_metrics_mql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchOp) ProtoMessage() {}

func (x *FetchOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchOp.ProtoReflect.Descriptor instead.
func (*FetchOp) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{1}
}

func (x *FetchOp) GetResourceType() string {
	if x != nil {
		return x.ResourceType
	}
	return ""
}

func (x *FetchOp) GetMetricType() string {
	if x != nil {
		return x.MetricType
	}
	return ""
}

// PipeOp is one stage in the processing pipeline after fetch.
type PipeOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Op:
	//
	//	*PipeOp_Filter
	//	*PipeOp_Align
	//	*PipeOp_Every
	//	*PipeOp_GroupBy
	Op            isPipeOp_Op `protobuf_oneof:"op"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipeOp) Reset() {
	*x = PipeOp{}
	mi := &file_metrics_mql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipeOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipeOp) ProtoMessage() {}

func (x *PipeOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipeOp.ProtoReflect.Descriptor instead.
func (*PipeOp) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{2}
}

func (x *PipeOp) GetOp() isPipeOp_Op {
	if x != nil {
		return x.Op
	}
	return nil
}

func (x *PipeOp) GetFilter() *FilterOp {
	if x != nil {
		if x, ok := x.Op.(*PipeOp_Filter); ok {
			return x.Filter
		}
	}
	return nil
}

func (x *PipeOp) GetAlign() *AlignOp {
	if x != nil {
		if x, ok := x.Op.(*PipeOp_Align); ok {
			return x.Align
		}
	}
	return nil
}

func (x *PipeOp) GetEvery() *EveryOp {
	if x != nil {
		if x, ok := x.Op.(*PipeOp_Every); ok {
			return x.Every
		}
	}
	return nil
}

func (x *PipeOp) GetGroupBy() *GroupByOp {
	if x != nil {
		if x, ok := x.Op.(*PipeOp_GroupBy); ok {
			return x.GroupBy
		}
	}
	return nil
}

type isPipeOp_Op interface {
	isPipeOp_Op()
}

type PipeOp_Filter struct {
	Filter *FilterOp `protobuf:"bytes,1,opt,name=filter,proto3,oneof"`
}

type PipeOp_Align struct {
	Align *AlignOp `protobuf:"bytes,2,opt,name=align,proto3,oneof"`
}

type PipeOp_Every struct {
	Every *EveryOp `protobuf:"bytes,3,opt,name=every,proto3,oneof"`
}

type PipeOp_GroupBy struct {
	GroupBy *GroupByOp `protobuf:"bytes,4,opt,name=group_by,json=groupBy,proto3,oneof"`
}

func (*PipeOp_Filter) isPipeOp_Op() {}

func (*PipeOp_Align) isPipeOp_Op() {}

func (*PipeOp_Every) isPipeOp_Op() {}

func (*PipeOp_GroupBy) isPipeOp_Op() {}

// FilterOp retains only time series whose labels match the predicate.
// Maps to: filter <predicate>
type FilterOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Predicate     *Predicate             `protobuf:"bytes,1,opt,name=predicate,proto3" json:"predicate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FilterOp) Reset() {
	*x = FilterOp{}
	mi := &file_metrics_mql_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FilterOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FilterOp) ProtoMessage() {}

func (x *FilterOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FilterOp.ProtoReflect.Descriptor instead.
func (*FilterOp) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{3}
}

func (x *FilterOp) GetPredicate() *Predicate {
	if x != nil {
		return x.Predicate
	}
	return nil
}

// AlignOp aligns each time series into fixed-width buckets.
// Maps to: align <aligner>(<period>)
type AlignOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Aligner       Aligner                `protobuf:"varint,1,opt,name=aligner,proto3,enum=metrics.Aligner" json:"aligner,omitempty"`
	Period        *durationpb.Duration   `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignOp) Reset() {
	*x = AlignOp{}
	mi := &file_metrics_mql_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignOp) ProtoMessage() {}

func (x *AlignOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignOp.ProtoReflect.Descriptor instead.
func (*AlignOp) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{4}
}

func (x *AlignOp) GetAligner() Aligner {
	if x != nil {
		return x.Aligner
	}
	return Aligner_ALIGN_NONE
}

func (x *AlignOp) GetPeriod() *durationpb.Duration {
	if x != nil {
		return x.Period
	}
	return nil
}

// EveryOp overrides the output sampling period without changing the aligner.
// When absent the period from AlignOp is used.
// Maps to: every <period>
type EveryOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Period        *durationpb.Duration   `protobuf:"bytes,1,opt,name=period,proto3" json:"period,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EveryOp) Reset() {
	*x = EveryOp{}
	mi := &file_metrics_mql_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EveryOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EveryOp) ProtoMessage() {}

func (x *EveryOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EveryOp.ProtoReflect.Descriptor instead.
func (*EveryOp) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{5}
}

func (x *EveryOp) GetPeriod() *durationpb.Duration {
	if x != nil {
		return x.Period
	}
	return nil
}

// GroupByOp reduces multiple series to fewer series, grouped by label keys.
// Maps to: group_by [<labels>], <reducer>()
type GroupByOp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted label paths to preserve, e.g. "metric.labels.zone".
	// Series are grouped by the Cartesian product of these values.
	LabelKeys     []string `protobuf:"bytes,1,rep,name=label_keys,json=labelKeys,proto3" json:"label_keys,omitempty"`
	Reducer       Reducer  `protobuf:"varint,2,opt,name=reducer,proto3,enum=metrics.Reducer" json:"reducer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupByOp) Reset() {
	*x = GroupByOp{}
	mi := &file_metrics_mql_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupByOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupByOp) ProtoMessage() {}

func (x *GroupByOp) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupByOp.ProtoReflect.Descriptor instead.
func (*GroupByOp) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{6}
}

func (x *GroupByOp) GetLabelKeys() []string {
	if x != nil {
		return x.LabelKeys
	}
	return nil
}

func (x *GroupByOp) GetReducer() Reducer {
	if x != nil {
		return x.Reducer
	}
	return Reducer_REDUCE_NONE
}

// TimeRange bounds the query window.
// Maps to: within <duration> (relative) or an explicit [start, end] range.
type TimeRange struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Range:
	//
	//	*TimeRange_Relative
	//	*TimeRange_Absolute
	Range         isTimeRange_Range `protobuf_oneof:"range"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeRange) Reset() {
	*x = TimeRange{}
	mi := &file_metrics_mql_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeRange) ProtoMessage() {}

func (x *TimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeRange.ProtoReflect.Descriptor instead.
func (*TimeRange) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{7}
}

func (x *TimeRange) GetRange() isTimeRange_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *TimeRange) GetRelative() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Range.(*TimeRange_Relative); ok {
			return x.Relative
		}
	}
	return nil
}

func (x *TimeRange) GetAbsolute() *AbsoluteRange {
	if x != nil {
		if x, ok := x.Range.(*TimeRange_Absolute); ok {
			return x.Absolute
		}
	}
	return nil
}

type isTimeRange_Range interface {
	isTimeRange_Range()
}

type TimeRange_Relative struct {
	// Relative: look back this far from now. E.g. "within 1h" → 3600s.
	Relative *durationpb.Duration `protobuf:"bytes,1,opt,name=relative,proto3,oneof"`
}

type TimeRange_Absolute struct {
	// Absolute: explicit start/end timestamps.
	Absolute *AbsoluteRange `protobuf:"bytes,2,opt,name=absolute,proto3,oneof"`
}

func (*TimeRange_Relative) isTimeRange_Range() {}

func (*TimeRange_Absolute) isTimeRange_Range() {}

type AbsoluteRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AbsoluteRange) Reset() {
	*x = AbsoluteRange{}
	mi := &file_metrics_mql_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AbsoluteRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AbsoluteRange) ProtoMessage() {}

func (x *AbsoluteRange) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AbsoluteRange.ProtoReflect.Descriptor instead.
func (*AbsoluteRange) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{8}
}

func (x *AbsoluteRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *AbsoluteRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

// Predicate is a boolean expression over metric/resource label values.
type Predicate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Expr:
	//
	//	*Predicate_Comparison
	//	*Predicate_Logical
	//	*Predicate_Not
	Expr          isPredicate_Expr `protobuf_oneof:"expr"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Predicate) Reset() {
	*x = Predicate{}
	mi := &file_metrics_mql_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Predicate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Predicate) ProtoMessage() {}

func (x *Predicate) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Predicate.ProtoReflect.Descriptor instead.
func (*Predicate) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{9}
}

func (x *Predicate) GetExpr() isPredicate_Expr {
	if x != nil {
		return x.Expr
	}
	return nil
}

func (x *Predicate) GetComparison() *ComparisonExpr {
	if x != nil {
		if x, ok := x.Expr.(*Predicate_Comparison); ok {
			return x.Comparison
		}
	}
	return nil
}

func (x *Predicate) GetLogical() *LogicalExpr {
	if x != nil {
		if x, ok := x.Expr.(*Predicate_Logical); ok {
			return x.Logical
		}
	}
	return nil
}

func (x *Predicate) GetNot() *NotExpr {
	if x != nil {
		if x, ok := x.Expr.(*Predicate_Not); ok {
			return x.Not
		}
	}
	return nil
}

type isPredicate_Expr interface {
	isPredicate_Expr()
}

type Predicate_Comparison struct {
	Comparison *ComparisonExpr `protobuf:"bytes,1,opt,name=comparison,proto3,oneof"`
}

type Predicate_Logical struct {
	Logical *LogicalExpr `protobuf:"bytes,2,opt,name=logical,proto3,oneof"`
}

type Predicate_Not struct {
	Not *NotExpr `protobuf:"bytes,3,opt,name=not,proto3,oneof"`
}

func (*Predicate_Comparison) isPredicate_Expr() {}

func (*Predicate_Logical) isPredicate_Expr() {}

func (*Predicate_Not) isPredicate_Expr() {}

// ComparisonExpr compares a label path against a literal value.
// e.g. metric.labels.instance_name =~ "my-.*"
type ComparisonExpr struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Dotted path to the label, e.g. "metric.labels.zone".
	LabelPath     string       `protobuf:"bytes,1,opt,name=label_path,json=labelPath,proto3" json:"label_path,omitempty"`
	Op            ComparisonOp `protobuf:"varint,2,opt,name=op,proto3,enum=mql.ComparisonOp" json:"op,omitempty"`
	Rhs           *Value       `protobuf:"bytes,3,opt,name=rhs,proto3" json:"rhs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ComparisonExpr) Reset() {
	*x = ComparisonExpr{}
	mi := &file_metrics_mql_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ComparisonExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComparisonExpr) ProtoMessage() {}

func (x *ComparisonExpr) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComparisonExpr.ProtoReflect.Descriptor instead.
func (*ComparisonExpr) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{10}
}

func (x *ComparisonExpr) GetLabelPath() string {
	if x != nil {
		return x.LabelPath
	}
	return ""
}

func (x *ComparisonExpr) GetOp() ComparisonOp {
	if x != nil {
		return x.Op
	}
	return ComparisonOp_EQ
}

func (x *ComparisonExpr) GetRhs() *Value {
	if x != nil {
		return x.Rhs
	}
	return nil
}

// LogicalExpr combines two or more predicates with AND or OR.
type LogicalExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            LogicalOp              `protobuf:"varint,1,opt,name=op,proto3,enum=mql.LogicalOp" json:"op,omitempty"`
	Operands      []*Predicate           `protobuf:"bytes,2,rep,name=operands,proto3" json:"operands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogicalExpr) Reset() {
	*x = LogicalExpr{}
	mi := &file_metrics_mql_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogicalExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogicalExpr) ProtoMessage() {}

func (x *LogicalExpr) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogicalExpr.ProtoReflect.Descriptor instead.
func (*LogicalExpr) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{11}
}

func (x *LogicalExpr) GetOp() LogicalOp {
	if x != nil {
		return x.Op
	}
	return LogicalOp_AND
}

func (x *LogicalExpr) GetOperands() []*Predicate {
	if x != nil {
		return x.Operands
	}
	return nil
}

// NotExpr negates a predicate.
type NotExpr struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operand       *Predicate             `protobuf:"bytes,1,opt,name=operand,proto3" json:"operand,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotExpr) Reset() {
	*x = NotExpr{}
	mi := &file_metrics_mql_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotExpr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotExpr) ProtoMessage() {}

func (x *NotExpr) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotExpr.ProtoReflect.Descriptor instead.
func (*NotExpr) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{12}
}

func (x *NotExpr) GetOperand() *Predicate {
	if x != nil {
		return x.Operand
	}
	return nil
}

// Value is a scalar literal used as the right-hand side of a comparison.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to V:
	//
	//	*Value_StringValue
	//	*Value_NumberValue
	//	*Value_BoolValue
	V             isValue_V `protobuf_oneof:"v"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_metrics_mql_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_mql_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_metrics_mql_proto_rawDescGZIP(), []int{13}
}

func (x *Value) GetV() isValue_V {
	if x != nil {
		return x.V
	}
	return nil
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.V.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetNumberValue() float64 {
	if x != nil {
		if x, ok := x.V.(*Value_NumberValue); ok {
			return x.NumberValue
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.V.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

type isValue_V interface {
	isValue_V()
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_NumberValue struct {
	NumberValue float64 `protobuf:"fixed64,2,opt,name=number_value,json=numberValue,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,3,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

func (*Value_StringValue) isValue_V() {}

func (*Value_NumberValue) isValue_V() {}

func (*Value_BoolValue) isValue_V() {}

var File_metrics_mql_proto protoreflect.FileDescriptor

const file_metrics_mql_proto_rawDesc = "" +
	"\n" +
	"\x11metrics/mql.proto\x12\x03mql\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19metrics/aggregation.proto\"\x87\x01\n" +
	"\tQueryPlan\x12\"\n" +
	"\x05fetch\x18\x01 \x01(\v2\f.mql.FetchOpR\x05fetch\x12'\n" +
	"\bpipeline\x18\x02 \x03(\v2\v.mql.PipeOpR\bpipeline\x12-\n" +
	"\n" +
	"time_range\x18\x03 \x01(\v2\x0e.mql.TimeRangeR\ttimeRange\"O\n" +
	"\aFetchOp\x12#\n" +
	"\rresource_type\x18\x01 \x01(\tR\fresourceType\x12\x1f\n" +
	"\vmetric_type\x18\x02 \x01(\tR\n" +
	"metricType\"\xb0\x01\n" +
	"\x06PipeOp\x12'\n" +
	"\x06filter\x18\x01 \x01(\v2\r.mql.FilterOpH\x00R\x06filter\x12$\n" +
	"\x05align\x18\x02 \x01(\v2\f.mql.AlignOpH\x00R\x05align\x12$\n" +
	"\x05every\x18\x03 \x01(\v2\f.mql.EveryOpH\x00R\x05every\x12+\n" +
	"\bgroup_by\x18\x04 \x01(\v2\x0e.mql.GroupByOpH\x00R\agroupByB\x04\n" +
	"\x02op\"8\n" +
	"\bFilterOp\x12,\n" +
	"\tpredicate\x18\x01 \x01(\v2\x0e.mql.PredicateR\tpredicate\"h\n" +
	"\aAlignOp\x12*\n" +
	"\aaligner\x18\x01 \x01(\x0e2\x10.metrics.AlignerR\aaligner\x121\n" +
	"\x06period\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x06period\"<\n" +
	"\aEveryOp\x121\n" +
	"\x06period\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x06period\"V\n" +
	"\tGroupByOp\x12\x1d\n" +
	"\n" +
	"label_keys\x18\x01 \x03(\tR\tlabelKeys\x12*\n" +
	"\areducer\x18\x02 \x01(\x0e2\x10.metrics.ReducerR\areducer\"\x7f\n" +
	"\tTimeRange\x127\n" +
	"\brelative\x18\x01 \x01(\v2\x19.google.protobuf.DurationH\x00R\brelative\x120\n" +
	"\babsolute\x18\x02 \x01(\v2\x12.mql.AbsoluteRangeH\x00R\babsoluteB\a\n" +
	"\x05range\"o\n" +
	"\rAbsoluteRange\x120\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12,\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x03end\"\x9a\x01\n" +
	"\tPredicate\x125\n" +
	"\n" +
	"comparison\x18\x01 \x01(\v2\x13.mql.ComparisonExprH\x00R\n" +
	"comparison\x12,\n" +
	"\alogical\x18\x02 \x01(\v2\x10.mql.LogicalExprH\x00R\alogical\x12 \n" +
	"\x03not\x18\x03 \x01(\v2\f.mql.NotExprH\x00R\x03notB\x06\n" +
	"\x04expr\"p\n" +
	"\x0eComparisonExpr\x12\x1d\n" +
	"\n" +
	"label_path\x18\x01 \x01(\tR\tlabelPath\x12!\n" +
	"\x02op\x18\x02 \x01(\x0e2\x11.mql.ComparisonOpR\x02op\x12\x1c\n" +
	"\x03rhs\x18\x03 \x01(\v2\n" +
	".mql.ValueR\x03rhs\"Y\n" +
	"\vLogicalExpr\x12\x1e\n" +
	"\x02op\x18\x01 \x01(\x0e2\x0e.mql.LogicalOpR\x02op\x12*\n" +
	"\boperands\x18\x02 \x03(\v2\x0e.mql.PredicateR\boperands\"3\n" +
	"\aNotExpr\x12(\n" +
	"\aoperand\x18\x01 \x01(\v2\x0e.mql.PredicateR\aoperand\"w\n" +
	"\x05Value\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12#\n" +
	"\fnumber_value\x18\x02 \x01(\x01H\x00R\vnumberValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x03 \x01(\bH\x00R\tboolValueB\x03\n" +
	"\x01v*R\n" +
	"\fComparisonOp\x12\x06\n" +
	"\x02EQ\x10\x00\x12\a\n" +
	"\x03NEQ\x10\x01\x12\x06\n" +
	"\x02RE\x10\x02\x12\a\n" +
	"\x03NRE\x10\x03\x12\x06\n" +
	"\x02LT\x10\x04\x12\a\n" +
	"\x03LTE\x10\x05\x12\x06\n" +
	"\x02GT\x10\x06\x12\a\n" +
	"\x03GTE\x10\a*\x1c\n" +
	"\tLogicalOp\x12\a\n" +
	"\x03AND\x10\x00\x12\x06\n" +
	"\x02OR\x10\x01B6Z4github.com/accretional/grpc-server-config/pb/metricsb\x06proto3"

var (
	file_metrics_mql_proto_rawDescOnce sync.Once
	file_metrics_mql_proto_rawDescData []byte
)

func file_metrics_mql_proto_rawDescGZIP() []byte {
	file_metrics_mql_proto_rawDescOnce.Do(func() {
		file_metrics_mql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_mql_proto_rawDesc), len(file_metrics_mql_proto_rawDesc)))
	})
	return file_metrics_mql_proto_rawDescData
}

var file_metrics_mql_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_metrics_mql_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_metrics_mql_proto_goTypes = []any{
	(ComparisonOp)(0),             // 0: mql.ComparisonOp
	(LogicalOp)(0),                // 1: mql.LogicalOp
	(*QueryPlan)(nil),             // 2: mql.QueryPlan
	(*FetchOp)(nil),               // 3: mql.FetchOp
	(*PipeOp)(nil),                // 4: mql.PipeOp
	(*FilterOp)(nil),              // 5: mql.FilterOp
	(*AlignOp)(nil),               // 6: mql.AlignOp
	(*EveryOp)(nil),               // 7: mql.EveryOp
	(*GroupByOp)(nil),             // 8: mql.GroupByOp
	(*TimeRange)(nil),             // 9: mql.TimeRange
	(*AbsoluteRange)(nil),         // 10: mql.AbsoluteRange
	(*Predicate)(nil),             // 11: mql.Predicate
	(*ComparisonExpr)(nil),        // 12: mql.ComparisonExpr
	(*LogicalExpr)(nil),           // 13: mql.LogicalExpr
	(*NotExpr)(nil),               // 14: mql.NotExpr
	(*Value)(nil),                 // 15: mql.Value
	(Aligner)(0),                  // 16: metrics.Aligner
	(*durationpb.Duration)(nil),   // 17: google.protobuf.Duration
	(Reducer)(0),                  // 18: metrics.Reducer
	(*timestamppb.Timestamp)(nil), // 19: google.protobuf.Timestamp
}
var file_metrics_mql_proto_depIdxs = []int32{
	3,  // 0: mql.QueryPlan.fetch:type_name -> mql.FetchOp
	4,  // 1: mql.QueryPlan.pipeline:type_name -> mql.PipeOp
	9,  // 2: mql.QueryPlan.time_range:type_name -> mql.TimeRange
	5,  // 3: mql.PipeOp.filter:type_name -> mql.FilterOp
	6,  // 4: mql.PipeOp.align:type_name -> mql.AlignOp
	7,  // 5: mql.PipeOp.every:type_name -> mql.EveryOp
	8,  // 6: mql.PipeOp.group_by:type_name -> mql.GroupByOp
	11, // 7: mql.FilterOp.predicate:type_name -> mql.Predicate
	16, // 8: mql.AlignOp.aligner:type_name -> metrics.Aligner
	17, // 9: mql.AlignOp.period:type_name -> google.protobuf.Duration
	17, // 10: mql.EveryOp.period:type_name -> google.protobuf.Duration
	18, // 11: mql.GroupByOp.reducer:type_name -> metrics.Reducer
	17, // 12: mql.TimeRange.relative:type_name -> google.protobuf.Duration
	10, // 13: mql.TimeRange.absolute:type_name -> mql.AbsoluteRange
	19, // 14: mql.AbsoluteRange.start:type_name -> google.protobuf.Timestamp
	19, // 15: mql.AbsoluteRange.end:type_name -> google.protobuf.Timestamp
	12, // 16: mql.Predicate.comparison:type_name -> mql.ComparisonExpr
	13, // 17: mql.Predicate.logical:type_name -> mql.LogicalExpr
	14, // 18: mql.Predicate.not:type_name -> mql.NotExpr
	0,  // 19: mql.ComparisonExpr.op:type_name -> mql.ComparisonOp
	15, // 20: mql.ComparisonExpr.rhs:type_name -> mql.Value
	1,  // 21: mql.LogicalExpr.op:type_name -> mql.LogicalOp
	11, // 22: mql.LogicalExpr.operands:type_name -> mql.Predicate
	11, // 23: mql.NotExpr.operand:type_name -> mql.Predicate
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_metrics_mql_proto_init() }
func file_metrics_mql_proto_init() {
	if File_metrics_mql_proto != nil {
		return
	}
	file_metrics_aggregation_proto_init()
	file_metrics_mql_proto_msgTypes[2].OneofWrappers = []any{
		(*PipeOp_Filter)(nil),
		(*PipeOp_Align)(nil),
		(*PipeOp_Every)(nil),
		(*PipeOp_GroupBy)(nil),
	}
	file_metrics_mql_proto_msgTypes[7].OneofWrappers = []any{
		(*TimeRange_Relative)(nil),
		(*TimeRange_Absolute)(nil),
	}
	file_metrics_mql_proto_msgTypes[9].OneofWrappers = []any{
		(*Predicate_Comparison)(nil),
		(*Predicate_Logical)(nil),
		(*Predicate_Not)(nil),
	}
	file_metrics_mql_proto_msgTypes[13].OneofWrappers = []any{
		(*Value_StringValue)(nil),
		(*Value_NumberValue)(nil),
		(*Value_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_mql_proto_rawDesc), len(file_metrics_mql_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_mql_proto_goTypes,
		DependencyIndexes: file_metrics_mql_proto_depIdxs,
		EnumInfos:         file_metrics_mql_proto_enumTypes,
		MessageInfos:      file_metrics_mql_proto_msgTypes,
	}.Build()
	File_metrics_mql_proto = out.File
	file_metrics_mql_proto_goTypes = nil
	file_metrics_mql_proto_depIdxs = nil
}
