// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/query_service.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// MQL query string.
	// Example: fetch gce_instance::compute.googleapis.com/instance/cpu/utilization
	//
	//	| align mean(1m)
	//	| every 1m
	//	| group_by [resource.labels.zone], mean()
	//	| within 1h
	MqlQuery      string `protobuf:"bytes,1,opt,name=mql_query,json=mqlQuery,proto3" json:"mql_query,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_metrics_query_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_query_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_metrics_query_service_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetMqlQuery() string {
	if x != nil {
		return x.MqlQuery
	}
	return ""
}

// QueryResponse carries one aligned/reduced time series.
// The server streams one message per output series.
type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Series        *AnyTimeSeries         `protobuf:"bytes,1,opt,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_metrics_query_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_query_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_metrics_query_service_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetSeries() *AnyTimeSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_metrics_query_service_proto protoreflect.FileDescriptor

const file_metrics_query_service_proto_rawDesc = "" +
	"\n" +
	"\x1bmetrics/query_service.proto\x12\ametrics\x1a!metrics/aggregation_service.proto\"+\n" +
	"\fQueryRequest\x12\x1b\n" +
	"\tmql_query\x18\x01 \x01(\tR\bmqlQuery\"?\n" +
	"\rQueryResponse\x12.\n" +
	"\x06series\x18\x01 \x01(\v2\x16.metrics.AnyTimeSeriesR\x06series2H\n" +
	"\fQueryService\x128\n" +
	"\x05Query\x12\x15.metrics.QueryRequest\x1a\x16.metrics.QueryResponse0\x01B6Z4github.com/accretional/grpc-server-config/pb/metricsb\x06proto3"

var (
	file_metrics_query_service_proto_rawDescOnce sync.Once
	file_metrics_query_service_proto_rawDescData []byte
)

func file_metrics_query_service_proto_rawDescGZIP() []byte {
	file_metrics_query_service_proto_rawDescOnce.Do(func() {
		file_metrics_query_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_query_service_proto_rawDesc), len(file_metrics_query_service_proto_rawDesc)))
	})
	return file_metrics_query_service_proto_rawDescData
}

var file_metrics_query_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_metrics_query_service_proto_goTypes = []any{
	(*QueryRequest)(nil),  // 0: metrics.QueryRequest
	(*QueryResponse)(nil), // 1: metrics.QueryResponse
	(*AnyTimeSeries)(nil), // 2: metrics.AnyTimeSeries
}
var file_metrics_query_service_proto_depIdxs = []int32{
	2, // 0: metrics.QueryResponse.series:type_name -> metrics.AnyTimeSeries
	0, // 1: metrics.QueryService.Query:input_type -> metrics.QueryRequest
	1, // 2: metrics.QueryService.Query:output_type -> metrics.QueryResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metrics_query_service_proto_init() }
func file_metrics_query_service_proto_init() {
	if File_metrics_query_service_proto != nil {
		return
	}
	file_metrics_aggregation_service_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_query_service_proto_rawDesc), len(file_metrics_query_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_query_service_proto_goTypes,
		DependencyIndexes: file_metrics_query_service_proto_depIdxs,
		MessageInfos:      file_metrics_query_service_proto_msgTypes,
	}.Build()
	File_metrics_query_service_proto = out.File
	file_metrics_query_service_proto_goTypes = nil
	file_metrics_query_service_proto_depIdxs = nil
}
