// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/resource.proto

package metrics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Resource is a typed, persistently-identified object — analogous to a file
// descriptor but with a persistent numeric id, an explicit ownership chain,
// and a type schema resolved via URI rather than a bare string.
//
// Resources replace Google's MonitoredResource {string type; map<string,string> labels}.
// Instead of a stringly-typed identifier whose valid label keys depend on the
// type string, a Resource carries real persistent identity and resolves its
// type schema through a FileDescriptorProto URI.
type Resource struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Persistent numeric identifier. Analogous to a file descriptor id;
	// survives renames and remains stable across the resource's lifetime.
	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable name for this resource instance (e.g. "web-01").
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Ownership chain. May correspond to a system resource or upstream session.
	// For example, a VM resource may be owned by a project resource.
	Owners []*Resource `protobuf:"bytes,3,rep,name=owners,proto3" json:"owners,omitempty"`
	// URI resolving to a FileDescriptorProto that describes this resource's type
	// schema. Replaces MonitoredResource.type (which was a bare string like
	// "gce_instance" with externally-documented label constraints).
	Type          string `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_metrics_resource_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_resource_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_metrics_resource_proto_rawDescGZIP(), []int{0}
}

func (x *Resource) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Resource) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resource) GetOwners() []*Resource {
	if x != nil {
		return x.Owners
	}
	return nil
}

func (x *Resource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_metrics_resource_proto protoreflect.FileDescriptor

const file_metrics_resource_proto_rawDesc = "" +
	"\n" +
	"\x16metrics/resource.proto\x12\bresource\"n\n" +
	"\bResource\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12*\n" +
	"\x06owners\x18\x03 \x03(\v2\x12.resource.ResourceR\x06owners\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04typeB6Z4github.com/accretional/grpc-server-config/pb/metricsb\x06proto3"

var (
	file_metrics_resource_proto_rawDescOnce sync.Once
	file_metrics_resource_proto_rawDescData []byte
)

func file_metrics_resource_proto_rawDescGZIP() []byte {
	file_metrics_resource_proto_rawDescOnce.Do(func() {
		file_metrics_resource_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_resource_proto_rawDesc), len(file_metrics_resource_proto_rawDesc)))
	})
	return file_metrics_resource_proto_rawDescData
}

var file_metrics_resource_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_metrics_resource_proto_goTypes = []any{
	(*Resource)(nil), // 0: resource.Resource
}
var file_metrics_resource_proto_depIdxs = []int32{
	0, // 0: resource.Resource.owners:type_name -> resource.Resource
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_metrics_resource_proto_init() }
func file_metrics_resource_proto_init() {
	if File_metrics_resource_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_resource_proto_rawDesc), len(file_metrics_resource_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_resource_proto_goTypes,
		DependencyIndexes: file_metrics_resource_proto_depIdxs,
		MessageInfos:      file_metrics_resource_proto_msgTypes,
	}.Build()
	File_metrics_resource_proto = out.File
	file_metrics_resource_proto_goTypes = nil
	file_metrics_resource_proto_depIdxs = nil
}
