// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: rate-limiting/ratelimit.proto

package ratelimit

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Scope int32

const (
	Scope_SCOPE_NONE Scope = 0
	// The rate limit applies at the grpc-server level
	Scope_Server Scope = 1
	// Only applies to services corresponding to a matcher (TODO: figure out how to structure the matcher. Probably do it Envoy-style)
	Scope_Services Scope = 2 // Later add things like Identity, IP, etc.
)

// Enum value maps for Scope.
var (
	Scope_name = map[int32]string{
		0: "SCOPE_NONE",
		1: "Server",
		2: "Services",
	}
	Scope_value = map[string]int32{
		"SCOPE_NONE": 0,
		"Server":     1,
		"Services":   2,
	}
)

func (x Scope) Enum() *Scope {
	p := new(Scope)
	*p = x
	return p
}

func (x Scope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Scope) Descriptor() protoreflect.EnumDescriptor {
	return file_rate_limiting_ratelimit_proto_enumTypes[0].Descriptor()
}

func (Scope) Type() protoreflect.EnumType {
	return &file_rate_limiting_ratelimit_proto_enumTypes[0]
}

func (x Scope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Scope.Descriptor instead.
func (Scope) EnumDescriptor() ([]byte, []int) {
	return file_rate_limiting_ratelimit_proto_rawDescGZIP(), []int{0}
}

type Interval int32

const (
	Interval_INTERVAL_NONE Interval = 0
	// I think this is the default for golangs rate-limiting utils?
	Interval_Rolling Interval = 1
	// When the rate limit accumulates monotonically until it resets to 0 at a particular time.
	// I DO NOT recommend using this in most cases except where some other dependency makes specific times relevant for rate limits (literally exemplifying the problem). You might think these are "simpler" but they are definitely NOT simpler than rolling/windowing far as rate limiting is concerned.
	// The problem is that hard resets and timeouts do not model the actual problem trying to be solved by rate limiting - excessive point in time load. And they are infectious, because exhausting them and needing to wait for something to cool down causes every dependency to have to fold in those specific time-handling implementations, oftentimes in a user-facing or pretty structural way.
	// PLEASE do not use this unless it is absolutely necessary
	Interval_Reset Interval = 2
)

// Enum value maps for Interval.
var (
	Interval_name = map[int32]string{
		0: "INTERVAL_NONE",
		1: "Rolling",
		2: "Reset",
	}
	Interval_value = map[string]int32{
		"INTERVAL_NONE": 0,
		"Rolling":       1,
		"Reset":         2,
	}
)

func (x Interval) Enum() *Interval {
	p := new(Interval)
	*p = x
	return p
}

func (x Interval) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Interval) Descriptor() protoreflect.EnumDescriptor {
	return file_rate_limiting_ratelimit_proto_enumTypes[1].Descriptor()
}

func (Interval) Type() protoreflect.EnumType {
	return &file_rate_limiting_ratelimit_proto_enumTypes[1]
}

func (x Interval) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Interval.Descriptor instead.
func (Interval) EnumDescriptor() ([]byte, []int) {
	return file_rate_limiting_ratelimit_proto_rawDescGZIP(), []int{1}
}

type RateLimit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Scope         Scope                  `protobuf:"varint,3,opt,name=scope,proto3,enum=ratelimit.Scope" json:"scope,omitempty"`
	Kind          Interval               `protobuf:"varint,4,opt,name=kind,proto3,enum=ratelimit.Interval" json:"kind,omitempty"`
	Limit         int64                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,6,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RateLimit) Reset() {
	*x = RateLimit{}
	mi := &file_rate_limiting_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RateLimit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RateLimit) ProtoMessage() {}

func (x *RateLimit) ProtoReflect() protoreflect.Message {
	mi := &file_rate_limiting_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RateLimit.ProtoReflect.Descriptor instead.
func (*RateLimit) Descriptor() ([]byte, []int) {
	return file_rate_limiting_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *RateLimit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RateLimit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RateLimit) GetScope() Scope {
	if x != nil {
		return x.Scope
	}
	return Scope_SCOPE_NONE
}

func (x *RateLimit) GetKind() Interval {
	if x != nil {
		return x.Kind
	}
	return Interval_INTERVAL_NONE
}

func (x *RateLimit) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *RateLimit) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

var File_rate_limiting_ratelimit_proto protoreflect.FileDescriptor

const file_rate_limiting_ratelimit_proto_rawDesc = "" +
	"\n" +
	"\x1drate-limiting/ratelimit.proto\x12\tratelimit\x1a\x1egoogle/protobuf/duration.proto\"\xdf\x01\n" +
	"\tRateLimit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12&\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x10.ratelimit.ScopeR\x05scope\x12'\n" +
	"\x04kind\x18\x04 \x01(\x0e2\x13.ratelimit.IntervalR\x04kind\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x03R\x05limit\x125\n" +
	"\bduration\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\bduration*1\n" +
	"\x05Scope\x12\x0e\n" +
	"\n" +
	"SCOPE_NONE\x10\x00\x12\n" +
	"\n" +
	"\x06Server\x10\x01\x12\f\n" +
	"\bServices\x10\x02*5\n" +
	"\bInterval\x12\x11\n" +
	"\rINTERVAL_NONE\x10\x00\x12\v\n" +
	"\aRolling\x10\x01\x12\t\n" +
	"\x05Reset\x10\x02B8Z6github.com/accretional/grpc-server-config/pb/ratelimitb\x06proto3"

var (
	file_rate_limiting_ratelimit_proto_rawDescOnce sync.Once
	file_rate_limiting_ratelimit_proto_rawDescData []byte
)

func file_rate_limiting_ratelimit_proto_rawDescGZIP() []byte {
	file_rate_limiting_ratelimit_proto_rawDescOnce.Do(func() {
		file_rate_limiting_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rate_limiting_ratelimit_proto_rawDesc), len(file_rate_limiting_ratelimit_proto_rawDesc)))
	})
	return file_rate_limiting_ratelimit_proto_rawDescData
}

var file_rate_limiting_ratelimit_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_rate_limiting_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_rate_limiting_ratelimit_proto_goTypes = []any{
	(Scope)(0),                  // 0: ratelimit.Scope
	(Interval)(0),               // 1: ratelimit.Interval
	(*RateLimit)(nil),           // 2: ratelimit.RateLimit
	(*durationpb.Duration)(nil), // 3: google.protobuf.Duration
}
var file_rate_limiting_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.RateLimit.scope:type_name -> ratelimit.Scope
	1, // 1: ratelimit.RateLimit.kind:type_name -> ratelimit.Interval
	3, // 2: ratelimit.RateLimit.duration:type_name -> google.protobuf.Duration
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_rate_limiting_ratelimit_proto_init() }
func file_rate_limiting_ratelimit_proto_init() {
	if File_rate_limiting_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rate_limiting_ratelimit_proto_rawDesc), len(file_rate_limiting_ratelimit_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rate_limiting_ratelimit_proto_goTypes,
		DependencyIndexes: file_rate_limiting_ratelimit_proto_depIdxs,
		EnumInfos:         file_rate_limiting_ratelimit_proto_enumTypes,
		MessageInfos:      file_rate_limiting_ratelimit_proto_msgTypes,
	}.Build()
	File_rate_limiting_ratelimit_proto = out.File
	file_rate_limiting_ratelimit_proto_goTypes = nil
	file_rate_limiting_ratelimit_proto_depIdxs = nil
}
