// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: logging/log.proto

package logging

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogLevel int32

const (
	// NB I think we should use this log level as a way to hide, soft-delete, or mark for deletion
	LogLevel_None LogLevel = 0
	// Info, Warn, Error are user-generated and used to distinguish between nominal/expected states (Info), undesirable states (Warn), and invalid/rejected states (Error)
	// Use Info for routine or non-problematic log messages. Default to using this and only escalate to Warn/Error if there is something that someone needs to see. Default to NOT logging useless/overly noisy/poor signal/noise logs if possible, because logs (and the load from moving them around) are not free.
	LogLevel_Info LogLevel = 1
	// Things you may want to use Warn for: outdated package or upgrade notices, missing/ignored/suboptimal configurations, compute resources running out, using something unimplemented/unsupported/unstable
	// Warn logs should always be user-facing and actionable/fixable. DO NOT use warn for routine (eg server shutdown) or unactionable/expeccted (eg logging the server build date) states.
	// A warn log should mean "you may want to look into this" or "you should look into this but it's not urgent" not just "high visibility" or "data that may or may not be concerning" (if the data isn't bad use Info; only use Warn if it actually is bad)
	LogLevel_Warn LogLevel = 2
	// Error logs should also be user-facing and actionable/fixable but they should mean "this shouldn't happen" or "can't do that" or "something failed". "you should look into this" or "you should fix this"
	// DO NOT use Error for trivially recoverable or actually-expected states. DO NOT use Error for low-level development/implementation errors. Don't get confused by golang error handling and think you need to emit an Error structured log every time they happen.
	// Error logs need to be meaningful to clients - that is actually extremely important because they are a major part of the product UX/interface exposed to users. DO NOT write error logs that use internal jargon/terms or concern themselves with non-customer-facing errors.
	// DO write Error logs that clearly explain what went wrong and ALWAYS enough information to communicate what should be done to fix it (if possible). DO include 1-2 links to external resources (eg documentation or one of the things that went wrong/was implicated, eg the client server) to help users if relevant.
	LogLevel_Error LogLevel = 3
	// use for shutdown logs and fatal/unrecoverable errors. DO NOT use Fatal log levels for recoverable or "related" errors (those should be Error; the Fatal logs should only be for the state/condition/error that is specifically unrecoverable and causnig a shutdown/cleanup)
	LogLevel_Fatal LogLevel = 4
	// TBD but I think we should allow Alerts to be filed directly (and when filed the "normal" way out-of-the-loop, also filed this way to bring them into the logging world) from code. This would be pretty useful for development/prototyping and a good way to avoid the cruft of doing it indirectly (eg by having something watching for a specific metric or log contents, because only that type of structure can file alerts)
	LogLevel_Alert LogLevel = 5
	// TBD but I think Alarms should be basically just Alerts, but urgent/time-sensitive. In my mind an alert may just get pushed via notifications/email some report in some cases, but an alarm is something that means "this must be handled/mitigated ASAP" or "you need to react to this problem and triage its urgency/importance ASAP, and then can turn off the alarm"
	LogLevel_Alarm LogLevel = 6
	// Infrastructure / non-user logging from an underlying service provider
	// If something is worth warning/erroring, we should just use regular Warn/Error logs I think, because they're relevant to the user in the same way their own would be.
	LogLevel_System LogLevel = 7
	// TBD but I think while System logs should be automated/come from software, actual messages from the platform (eg about credits expiring or some upcoming service disruption) should be categorized as Notices (or something similar).
	// But it also sounds reasonable for notices to be used for any hand-written log (even if bulk sent, it was done outside the context of infrastructure/the normal application). Without good tooling would be pretty clunky for humans but could be very useful if given a CLI; also seems very useful for LLMs.
	LogLevel_Notice LogLevel = 8
	// Not sure exactly how to use this yet, need to brush up on how other systems use it
	LogLevel_Debug LogLevel = 9 // Also need some new ones for LLMs: maybe Note or Report . The idea being that LLMs and/or their harness can fire off bespoke logs while debugging or checking/changing/deploying something so that their logs/progress gets tracked in the same stream as the other software. But they can probably just re-use Notice though.
)

// Enum value maps for LogLevel.
var (
	LogLevel_name = map[int32]string{
		0: "None",
		1: "Info",
		2: "Warn",
		3: "Error",
		4: "Fatal",
		5: "Alert",
		6: "Alarm",
		7: "System",
		8: "Notice",
		9: "Debug",
	}
	LogLevel_value = map[string]int32{
		"None":   0,
		"Info":   1,
		"Warn":   2,
		"Error":  3,
		"Fatal":  4,
		"Alert":  5,
		"Alarm":  6,
		"System": 7,
		"Notice": 8,
		"Debug":  9,
	}
)

func (x LogLevel) Enum() *LogLevel {
	p := new(LogLevel)
	*p = x
	return p
}

func (x LogLevel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogLevel) Descriptor() protoreflect.EnumDescriptor {
	return file_logging_log_proto_enumTypes[0].Descriptor()
}

func (LogLevel) Type() protoreflect.EnumType {
	return &file_logging_log_proto_enumTypes[0]
}

func (x LogLevel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogLevel.Descriptor instead.
func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return file_logging_log_proto_rawDescGZIP(), []int{0}
}

type Log struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Level    LogLevel               `protobuf:"varint,1,opt,name=level,proto3,enum=logging.LogLevel" json:"level,omitempty"`
	Contents string                 `protobuf:"bytes,2,opt,name=contents,proto3" json:"contents,omitempty"`
	// TODO replace with our own timestamp type
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_logging_log_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_logging_log_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_logging_log_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_None
}

func (x *Log) GetContents() string {
	if x != nil {
		return x.Contents
	}
	return ""
}

func (x *Log) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_logging_log_proto protoreflect.FileDescriptor

const file_logging_log_proto_rawDesc = "" +
	"\n" +
	"\x11logging/log.proto\x12\alogging\x1a\x1fgoogle/protobuf/timestamp.proto\"\x85\x01\n" +
	"\x03Log\x12'\n" +
	"\x05level\x18\x01 \x01(\x0e2\x11.logging.LogLevelR\x05level\x12\x1a\n" +
	"\bcontents\x18\x02 \x01(\tR\bcontents\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt*w\n" +
	"\bLogLevel\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04Info\x10\x01\x12\b\n" +
	"\x04Warn\x10\x02\x12\t\n" +
	"\x05Error\x10\x03\x12\t\n" +
	"\x05Fatal\x10\x04\x12\t\n" +
	"\x05Alert\x10\x05\x12\t\n" +
	"\x05Alarm\x10\x06\x12\n" +
	"\n" +
	"\x06System\x10\a\x12\n" +
	"\n" +
	"\x06Notice\x10\b\x12\t\n" +
	"\x05Debug\x10\tB6Z4github.com/accretional/grpc-server-config/pb/loggingb\x06proto3"

var (
	file_logging_log_proto_rawDescOnce sync.Once
	file_logging_log_proto_rawDescData []byte
)

func file_logging_log_proto_rawDescGZIP() []byte {
	file_logging_log_proto_rawDescOnce.Do(func() {
		file_logging_log_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_logging_log_proto_rawDesc), len(file_logging_log_proto_rawDesc)))
	})
	return file_logging_log_proto_rawDescData
}

var file_logging_log_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_logging_log_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_logging_log_proto_goTypes = []any{
	(LogLevel)(0),                 // 0: logging.LogLevel
	(*Log)(nil),                   // 1: logging.Log
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_logging_log_proto_depIdxs = []int32{
	0, // 0: logging.Log.level:type_name -> logging.LogLevel
	2, // 1: logging.Log.created_at:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_logging_log_proto_init() }
func file_logging_log_proto_init() {
	if File_logging_log_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_logging_log_proto_rawDesc), len(file_logging_log_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_logging_log_proto_goTypes,
		DependencyIndexes: file_logging_log_proto_depIdxs,
		EnumInfos:         file_logging_log_proto_enumTypes,
		MessageInfos:      file_logging_log_proto_msgTypes,
	}.Build()
	File_logging_log_proto = out.File
	file_logging_log_proto_goTypes = nil
	file_logging_log_proto_depIdxs = nil
}
