// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/aggregation_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AnyTimeSeries wraps any of the three time series kinds in a oneof,
// allowing a single field to carry whichever kind the aligner produces.
// The output kind of Align may differ from the input kind:
//
//	ALIGN_DELTA on CumulativeTimeSeries  → DeltaTimeSeries
//	ALIGN_RATE  on Cumulative or Delta   → GaugeTimeSeries (DOUBLE)
//	All statistical aligners             → GaugeTimeSeries
type AnyTimeSeries struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Series:
	//
	//	*AnyTimeSeries_Gauge
	//	*AnyTimeSeries_Delta
	//	*AnyTimeSeries_Cumulative
	Series        isAnyTimeSeries_Series `protobuf_oneof:"series"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyTimeSeries) Reset() {
	*x = AnyTimeSeries{}
	mi := &file_metrics_aggregation_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyTimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyTimeSeries) ProtoMessage() {}

func (x *AnyTimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyTimeSeries.ProtoReflect.Descriptor instead.
func (*AnyTimeSeries) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_service_proto_rawDescGZIP(), []int{0}
}

func (x *AnyTimeSeries) GetSeries() isAnyTimeSeries_Series {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *AnyTimeSeries) GetGauge() *GaugeTimeSeries {
	if x != nil {
		if x, ok := x.Series.(*AnyTimeSeries_Gauge); ok {
			return x.Gauge
		}
	}
	return nil
}

func (x *AnyTimeSeries) GetDelta() *DeltaTimeSeries {
	if x != nil {
		if x, ok := x.Series.(*AnyTimeSeries_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *AnyTimeSeries) GetCumulative() *CumulativeTimeSeries {
	if x != nil {
		if x, ok := x.Series.(*AnyTimeSeries_Cumulative); ok {
			return x.Cumulative
		}
	}
	return nil
}

type isAnyTimeSeries_Series interface {
	isAnyTimeSeries_Series()
}

type AnyTimeSeries_Gauge struct {
	Gauge *GaugeTimeSeries `protobuf:"bytes,1,opt,name=gauge,proto3,oneof"`
}

type AnyTimeSeries_Delta struct {
	Delta *DeltaTimeSeries `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type AnyTimeSeries_Cumulative struct {
	Cumulative *CumulativeTimeSeries `protobuf:"bytes,3,opt,name=cumulative,proto3,oneof"`
}

func (*AnyTimeSeries_Gauge) isAnyTimeSeries_Series() {}

func (*AnyTimeSeries_Delta) isAnyTimeSeries_Series() {}

func (*AnyTimeSeries_Cumulative) isAnyTimeSeries_Series() {}

type AlignRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The time series to align.
	Input *AnyTimeSeries `protobuf:"bytes,1,opt,name=input,proto3" json:"input,omitempty"`
	// The aligner to apply. ALIGN_NONE returns the series unchanged.
	Aligner Aligner `protobuf:"varint,2,opt,name=aligner,proto3,enum=metrics.Aligner" json:"aligner,omitempty"`
	// Width of each alignment bucket. Required for all aligners except
	// ALIGN_NONE. Minimum 60s.
	AlignmentPeriod *durationpb.Duration `protobuf:"bytes,3,opt,name=alignment_period,json=alignmentPeriod,proto3" json:"alignment_period,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AlignRequest) Reset() {
	*x = AlignRequest{}
	mi := &file_metrics_aggregation_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignRequest) ProtoMessage() {}

func (x *AlignRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignRequest.ProtoReflect.Descriptor instead.
func (*AlignRequest) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_service_proto_rawDescGZIP(), []int{1}
}

func (x *AlignRequest) GetInput() *AnyTimeSeries {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *AlignRequest) GetAligner() Aligner {
	if x != nil {
		return x.Aligner
	}
	return Aligner_ALIGN_NONE
}

func (x *AlignRequest) GetAlignmentPeriod() *durationpb.Duration {
	if x != nil {
		return x.AlignmentPeriod
	}
	return nil
}

type AlignResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The aligned series. The kind may differ from AlignRequest.input; see
	// AnyTimeSeries for the mapping.
	Output        *AnyTimeSeries `protobuf:"bytes,1,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlignResponse) Reset() {
	*x = AlignResponse{}
	mi := &file_metrics_aggregation_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlignResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlignResponse) ProtoMessage() {}

func (x *AlignResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlignResponse.ProtoReflect.Descriptor instead.
func (*AlignResponse) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_service_proto_rawDescGZIP(), []int{2}
}

func (x *AlignResponse) GetOutput() *AnyTimeSeries {
	if x != nil {
		return x.Output
	}
	return nil
}

type ReduceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Input series to reduce. All series must:
	//   - be of the same kind (all Gauge, all Delta, or all Cumulative)
	//   - be already aligned to the same alignment_period
	//   - share the same Metric.type
	Series []*AnyTimeSeries `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	// The cross-series aggregation to apply. REDUCE_NONE is a no-op.
	Reducer Reducer `protobuf:"varint,2,opt,name=reducer,proto3,enum=metrics.Reducer" json:"reducer,omitempty"`
	// Label keys to preserve. Series are grouped by the Cartesian product of
	// these label values; all other label dimensions are dropped from output.
	// Empty means all series are collapsed into one output series (if possible).
	GroupByFields []string `protobuf:"bytes,3,rep,name=group_by_fields,json=groupByFields,proto3" json:"group_by_fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceRequest) Reset() {
	*x = ReduceRequest{}
	mi := &file_metrics_aggregation_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceRequest) ProtoMessage() {}

func (x *ReduceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceRequest.ProtoReflect.Descriptor instead.
func (*ReduceRequest) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_service_proto_rawDescGZIP(), []int{3}
}

func (x *ReduceRequest) GetSeries() []*AnyTimeSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

func (x *ReduceRequest) GetReducer() Reducer {
	if x != nil {
		return x.Reducer
	}
	return Reducer_REDUCE_NONE
}

func (x *ReduceRequest) GetGroupByFields() []string {
	if x != nil {
		return x.GroupByFields
	}
	return nil
}

type ReduceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// One output series per unique combination of group_by_fields label values.
	Series        []*AnyTimeSeries `protobuf:"bytes,1,rep,name=series,proto3" json:"series,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReduceResponse) Reset() {
	*x = ReduceResponse{}
	mi := &file_metrics_aggregation_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReduceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReduceResponse) ProtoMessage() {}

func (x *ReduceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_aggregation_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReduceResponse.ProtoReflect.Descriptor instead.
func (*ReduceResponse) Descriptor() ([]byte, []int) {
	return file_metrics_aggregation_service_proto_rawDescGZIP(), []int{4}
}

func (x *ReduceResponse) GetSeries() []*AnyTimeSeries {
	if x != nil {
		return x.Series
	}
	return nil
}

var File_metrics_aggregation_service_proto protoreflect.FileDescriptor

const file_metrics_aggregation_service_proto_rawDesc = "" +
	"\n" +
	"!metrics/aggregation_service.proto\x12\ametrics\x1a\x1egoogle/protobuf/duration.proto\x1a\x14metrics/metric.proto\x1a\x19metrics/aggregation.proto\"\xbe\x01\n" +
	"\rAnyTimeSeries\x120\n" +
	"\x05gauge\x18\x01 \x01(\v2\x18.metrics.GaugeTimeSeriesH\x00R\x05gauge\x120\n" +
	"\x05delta\x18\x02 \x01(\v2\x18.metrics.DeltaTimeSeriesH\x00R\x05delta\x12?\n" +
	"\n" +
	"cumulative\x18\x03 \x01(\v2\x1d.metrics.CumulativeTimeSeriesH\x00R\n" +
	"cumulativeB\b\n" +
	"\x06series\"\xae\x01\n" +
	"\fAlignRequest\x12,\n" +
	"\x05input\x18\x01 \x01(\v2\x16.metrics.AnyTimeSeriesR\x05input\x12*\n" +
	"\aaligner\x18\x02 \x01(\x0e2\x10.metrics.AlignerR\aaligner\x12D\n" +
	"\x10alignment_period\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0falignmentPeriod\"?\n" +
	"\rAlignResponse\x12.\n" +
	"\x06output\x18\x01 \x01(\v2\x16.metrics.AnyTimeSeriesR\x06output\"\x93\x01\n" +
	"\rReduceRequest\x12.\n" +
	"\x06series\x18\x01 \x03(\v2\x16.metrics.AnyTimeSeriesR\x06series\x12*\n" +
	"\areducer\x18\x02 \x01(\x0e2\x10.metrics.ReducerR\areducer\x12&\n" +
	"\x0fgroup_by_fields\x18\x03 \x03(\tR\rgroupByFields\"@\n" +
	"\x0eReduceResponse\x12.\n" +
	"\x06series\x18\x01 \x03(\v2\x16.metrics.AnyTimeSeriesR\x06series2\x87\x01\n" +
	"\x12AggregationService\x126\n" +
	"\x05Align\x12\x15.metrics.AlignRequest\x1a\x16.metrics.AlignResponse\x129\n" +
	"\x06Reduce\x12\x16.metrics.ReduceRequest\x1a\x17.metrics.ReduceResponseB.Z,github.com/accretional/grpc-server-config/pbb\x06proto3"

var (
	file_metrics_aggregation_service_proto_rawDescOnce sync.Once
	file_metrics_aggregation_service_proto_rawDescData []byte
)

func file_metrics_aggregation_service_proto_rawDescGZIP() []byte {
	file_metrics_aggregation_service_proto_rawDescOnce.Do(func() {
		file_metrics_aggregation_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_aggregation_service_proto_rawDesc), len(file_metrics_aggregation_service_proto_rawDesc)))
	})
	return file_metrics_aggregation_service_proto_rawDescData
}

var file_metrics_aggregation_service_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_metrics_aggregation_service_proto_goTypes = []any{
	(*AnyTimeSeries)(nil),        // 0: metrics.AnyTimeSeries
	(*AlignRequest)(nil),         // 1: metrics.AlignRequest
	(*AlignResponse)(nil),        // 2: metrics.AlignResponse
	(*ReduceRequest)(nil),        // 3: metrics.ReduceRequest
	(*ReduceResponse)(nil),       // 4: metrics.ReduceResponse
	(*GaugeTimeSeries)(nil),      // 5: metrics.GaugeTimeSeries
	(*DeltaTimeSeries)(nil),      // 6: metrics.DeltaTimeSeries
	(*CumulativeTimeSeries)(nil), // 7: metrics.CumulativeTimeSeries
	(Aligner)(0),                 // 8: metrics.Aligner
	(*durationpb.Duration)(nil),  // 9: google.protobuf.Duration
	(Reducer)(0),                 // 10: metrics.Reducer
}
var file_metrics_aggregation_service_proto_depIdxs = []int32{
	5,  // 0: metrics.AnyTimeSeries.gauge:type_name -> metrics.GaugeTimeSeries
	6,  // 1: metrics.AnyTimeSeries.delta:type_name -> metrics.DeltaTimeSeries
	7,  // 2: metrics.AnyTimeSeries.cumulative:type_name -> metrics.CumulativeTimeSeries
	0,  // 3: metrics.AlignRequest.input:type_name -> metrics.AnyTimeSeries
	8,  // 4: metrics.AlignRequest.aligner:type_name -> metrics.Aligner
	9,  // 5: metrics.AlignRequest.alignment_period:type_name -> google.protobuf.Duration
	0,  // 6: metrics.AlignResponse.output:type_name -> metrics.AnyTimeSeries
	0,  // 7: metrics.ReduceRequest.series:type_name -> metrics.AnyTimeSeries
	10, // 8: metrics.ReduceRequest.reducer:type_name -> metrics.Reducer
	0,  // 9: metrics.ReduceResponse.series:type_name -> metrics.AnyTimeSeries
	1,  // 10: metrics.AggregationService.Align:input_type -> metrics.AlignRequest
	3,  // 11: metrics.AggregationService.Reduce:input_type -> metrics.ReduceRequest
	2,  // 12: metrics.AggregationService.Align:output_type -> metrics.AlignResponse
	4,  // 13: metrics.AggregationService.Reduce:output_type -> metrics.ReduceResponse
	12, // [12:14] is the sub-list for method output_type
	10, // [10:12] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_metrics_aggregation_service_proto_init() }
func file_metrics_aggregation_service_proto_init() {
	if File_metrics_aggregation_service_proto != nil {
		return
	}
	file_metrics_metric_proto_init()
	file_metrics_aggregation_proto_init()
	file_metrics_aggregation_service_proto_msgTypes[0].OneofWrappers = []any{
		(*AnyTimeSeries_Gauge)(nil),
		(*AnyTimeSeries_Delta)(nil),
		(*AnyTimeSeries_Cumulative)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_aggregation_service_proto_rawDesc), len(file_metrics_aggregation_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_metrics_aggregation_service_proto_goTypes,
		DependencyIndexes: file_metrics_aggregation_service_proto_depIdxs,
		MessageInfos:      file_metrics_aggregation_service_proto_msgTypes,
	}.Build()
	File_metrics_aggregation_service_proto = out.File
	file_metrics_aggregation_service_proto_goTypes = nil
	file_metrics_aggregation_service_proto_depIdxs = nil
}
