// Adapted from google.api.Distribution (google/api/distribution.proto).
// Exemplar.attachments simplified: google.protobuf.Any replaced with a string
// label to avoid the heavyweight Any import. Typed attachments (e.g. trace IDs)
// can be added later via a typed oneof when needed.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/distribution.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Distribution contains summary statistics for a population of values and an
// optional histogram over a set of buckets.
//
// The underflow bucket (index 0) and overflow bucket (index N-1) are always
// present; the N-2 finite buckets sit between them. bucket_counts must have
// exactly as many entries as there are buckets implied by bucket_options.
type Distribution struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total number of values. Must equal sum(bucket_counts) when a histogram
	// is present.
	Count int64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Arithmetic mean of the values. Must be zero when count is zero.
	Mean float64 `protobuf:"fixed64,2,opt,name=mean,proto3" json:"mean,omitempty"`
	// Sum of squared deviations from the mean: Σ(x_i - mean)².
	// Computed via Welford's online algorithm. Must be zero when count is zero.
	SumOfSquaredDeviation float64 `protobuf:"fixed64,3,opt,name=sum_of_squared_deviation,json=sumOfSquaredDeviation,proto3" json:"sum_of_squared_deviation,omitempty"`
	// Observed min/max. Must not be set when count is zero.
	Range *Distribution_Range `protobuf:"bytes,4,opt,name=range,proto3" json:"range,omitempty"`
	// Histogram bucket boundaries. Omit when no histogram is needed.
	BucketOptions *Distribution_BucketOptions `protobuf:"bytes,6,opt,name=bucket_options,json=bucketOptions,proto3" json:"bucket_options,omitempty"`
	// Count per bucket, in bucket order (underflow first, overflow last).
	// Must have exactly as many entries as buckets defined by bucket_options.
	// Trailing zeros may be omitted.
	BucketCounts []int64 `protobuf:"varint,7,rep,packed,name=bucket_counts,json=bucketCounts,proto3" json:"bucket_counts,omitempty"`
	// Sampled exemplar points. Must be in increasing order of value.
	Exemplars     []*Distribution_Exemplar `protobuf:"bytes,10,rep,name=exemplars,proto3" json:"exemplars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution) Reset() {
	*x = Distribution{}
	mi := &file_metrics_distribution_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution) ProtoMessage() {}

func (x *Distribution) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution.ProtoReflect.Descriptor instead.
func (*Distribution) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0}
}

func (x *Distribution) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *Distribution) GetMean() float64 {
	if x != nil {
		return x.Mean
	}
	return 0
}

func (x *Distribution) GetSumOfSquaredDeviation() float64 {
	if x != nil {
		return x.SumOfSquaredDeviation
	}
	return 0
}

func (x *Distribution) GetRange() *Distribution_Range {
	if x != nil {
		return x.Range
	}
	return nil
}

func (x *Distribution) GetBucketOptions() *Distribution_BucketOptions {
	if x != nil {
		return x.BucketOptions
	}
	return nil
}

func (x *Distribution) GetBucketCounts() []int64 {
	if x != nil {
		return x.BucketCounts
	}
	return nil
}

func (x *Distribution) GetExemplars() []*Distribution_Exemplar {
	if x != nil {
		return x.Exemplars
	}
	return nil
}

// Range records the observed minimum and maximum of the population.
// Must not be present when count is zero.
type Distribution_Range struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Min           float64                `protobuf:"fixed64,1,opt,name=min,proto3" json:"min,omitempty"`
	Max           float64                `protobuf:"fixed64,2,opt,name=max,proto3" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution_Range) Reset() {
	*x = Distribution_Range{}
	mi := &file_metrics_distribution_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_Range) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_Range) ProtoMessage() {}

func (x *Distribution_Range) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_Range.ProtoReflect.Descriptor instead.
func (*Distribution_Range) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Distribution_Range) GetMin() float64 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *Distribution_Range) GetMax() float64 {
	if x != nil {
		return x.Max
	}
	return 0
}

// BucketOptions defines the histogram bucket boundaries.
// Exactly one variant must be set. The N+2 buckets (N finite + underflow +
// overflow) are contiguous and cover (-∞, +∞).
type Distribution_BucketOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Options:
	//
	//	*Distribution_BucketOptions_LinearBuckets
	//	*Distribution_BucketOptions_ExponentialBuckets
	//	*Distribution_BucketOptions_ExplicitBuckets
	Options       isDistribution_BucketOptions_Options `protobuf_oneof:"options"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution_BucketOptions) Reset() {
	*x = Distribution_BucketOptions{}
	mi := &file_metrics_distribution_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_BucketOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_BucketOptions) ProtoMessage() {}

func (x *Distribution_BucketOptions) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_BucketOptions.ProtoReflect.Descriptor instead.
func (*Distribution_BucketOptions) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0, 1}
}

func (x *Distribution_BucketOptions) GetOptions() isDistribution_BucketOptions_Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Distribution_BucketOptions) GetLinearBuckets() *Distribution_BucketOptions_Linear {
	if x != nil {
		if x, ok := x.Options.(*Distribution_BucketOptions_LinearBuckets); ok {
			return x.LinearBuckets
		}
	}
	return nil
}

func (x *Distribution_BucketOptions) GetExponentialBuckets() *Distribution_BucketOptions_Exponential {
	if x != nil {
		if x, ok := x.Options.(*Distribution_BucketOptions_ExponentialBuckets); ok {
			return x.ExponentialBuckets
		}
	}
	return nil
}

func (x *Distribution_BucketOptions) GetExplicitBuckets() *Distribution_BucketOptions_Explicit {
	if x != nil {
		if x, ok := x.Options.(*Distribution_BucketOptions_ExplicitBuckets); ok {
			return x.ExplicitBuckets
		}
	}
	return nil
}

type isDistribution_BucketOptions_Options interface {
	isDistribution_BucketOptions_Options()
}

type Distribution_BucketOptions_LinearBuckets struct {
	LinearBuckets *Distribution_BucketOptions_Linear `protobuf:"bytes,1,opt,name=linear_buckets,json=linearBuckets,proto3,oneof"`
}

type Distribution_BucketOptions_ExponentialBuckets struct {
	ExponentialBuckets *Distribution_BucketOptions_Exponential `protobuf:"bytes,2,opt,name=exponential_buckets,json=exponentialBuckets,proto3,oneof"`
}

type Distribution_BucketOptions_ExplicitBuckets struct {
	ExplicitBuckets *Distribution_BucketOptions_Explicit `protobuf:"bytes,3,opt,name=explicit_buckets,json=explicitBuckets,proto3,oneof"`
}

func (*Distribution_BucketOptions_LinearBuckets) isDistribution_BucketOptions_Options() {}

func (*Distribution_BucketOptions_ExponentialBuckets) isDistribution_BucketOptions_Options() {}

func (*Distribution_BucketOptions_ExplicitBuckets) isDistribution_BucketOptions_Options() {}

// Exemplar annotates a single sampled value within the distribution.
// Carries the value, observation time, and an optional human-readable label.
// Exemplars must be in increasing order of value.
type Distribution_Exemplar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The sampled value; determines which bucket this exemplar belongs to.
	Value float64 `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	// When the sample was observed.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Optional human-readable context (e.g. a trace ID or request path).
	// A typed attachment oneof can replace this when richer metadata is needed.
	Label         string `protobuf:"bytes,3,opt,name=label,proto3" json:"label,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution_Exemplar) Reset() {
	*x = Distribution_Exemplar{}
	mi := &file_metrics_distribution_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_Exemplar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_Exemplar) ProtoMessage() {}

func (x *Distribution_Exemplar) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_Exemplar.ProtoReflect.Descriptor instead.
func (*Distribution_Exemplar) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0, 2}
}

func (x *Distribution_Exemplar) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Distribution_Exemplar) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Distribution_Exemplar) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

// Linear: N+2 equal-width buckets.
//
//	Bucket 0 (underflow): (-∞, offset)
//	Bucket i (1..N):      [offset+(i-1)*width, offset+i*width)
//	Bucket N+1 (overflow):[offset+N*width, +∞)
type Distribution_BucketOptions_Linear struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NumFiniteBuckets int32                  `protobuf:"varint,1,opt,name=num_finite_buckets,json=numFiniteBuckets,proto3" json:"num_finite_buckets,omitempty"` // N, must be > 0
	Width            float64                `protobuf:"fixed64,2,opt,name=width,proto3" json:"width,omitempty"`                                                // must be > 0
	Offset           float64                `protobuf:"fixed64,3,opt,name=offset,proto3" json:"offset,omitempty"`                                              // lower bound of first finite bucket
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Distribution_BucketOptions_Linear) Reset() {
	*x = Distribution_BucketOptions_Linear{}
	mi := &file_metrics_distribution_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_BucketOptions_Linear) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_BucketOptions_Linear) ProtoMessage() {}

func (x *Distribution_BucketOptions_Linear) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_BucketOptions_Linear.ProtoReflect.Descriptor instead.
func (*Distribution_BucketOptions_Linear) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Distribution_BucketOptions_Linear) GetNumFiniteBuckets() int32 {
	if x != nil {
		return x.NumFiniteBuckets
	}
	return 0
}

func (x *Distribution_BucketOptions_Linear) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Distribution_BucketOptions_Linear) GetOffset() float64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Exponential: N+2 geometrically-growing buckets.
//
//	Bucket 0 (underflow): (-∞, scale)
//	Bucket i (1..N):      [scale*g^(i-1), scale*g^i)
//	Bucket N+1 (overflow):[scale*g^N, +∞)
type Distribution_BucketOptions_Exponential struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NumFiniteBuckets int32                  `protobuf:"varint,1,opt,name=num_finite_buckets,json=numFiniteBuckets,proto3" json:"num_finite_buckets,omitempty"` // N, must be > 0
	GrowthFactor     float64                `protobuf:"fixed64,2,opt,name=growth_factor,json=growthFactor,proto3" json:"growth_factor,omitempty"`              // g, must be > 1
	Scale            float64                `protobuf:"fixed64,3,opt,name=scale,proto3" json:"scale,omitempty"`                                                // must be > 0
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Distribution_BucketOptions_Exponential) Reset() {
	*x = Distribution_BucketOptions_Exponential{}
	mi := &file_metrics_distribution_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_BucketOptions_Exponential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_BucketOptions_Exponential) ProtoMessage() {}

func (x *Distribution_BucketOptions_Exponential) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_BucketOptions_Exponential.ProtoReflect.Descriptor instead.
func (*Distribution_BucketOptions_Exponential) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Distribution_BucketOptions_Exponential) GetNumFiniteBuckets() int32 {
	if x != nil {
		return x.NumFiniteBuckets
	}
	return 0
}

func (x *Distribution_BucketOptions_Exponential) GetGrowthFactor() float64 {
	if x != nil {
		return x.GrowthFactor
	}
	return 0
}

func (x *Distribution_BucketOptions_Exponential) GetScale() float64 {
	if x != nil {
		return x.Scale
	}
	return 0
}

// Explicit: buckets defined by a sorted list of boundary values.
//
//	Produces len(bounds)+1 buckets.
//	Bucket 0 (underflow): (-∞, bounds[0])
//	Bucket i (1..k-1):    [bounds[i-1], bounds[i])
//	Bucket k (overflow):  [bounds[k-1], +∞)
type Distribution_BucketOptions_Explicit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bounds        []float64              `protobuf:"fixed64,1,rep,packed,name=bounds,proto3" json:"bounds,omitempty"` // must be monotonically increasing
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Distribution_BucketOptions_Explicit) Reset() {
	*x = Distribution_BucketOptions_Explicit{}
	mi := &file_metrics_distribution_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Distribution_BucketOptions_Explicit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Distribution_BucketOptions_Explicit) ProtoMessage() {}

func (x *Distribution_BucketOptions_Explicit) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_distribution_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Distribution_BucketOptions_Explicit.ProtoReflect.Descriptor instead.
func (*Distribution_BucketOptions_Explicit) Descriptor() ([]byte, []int) {
	return file_metrics_distribution_proto_rawDescGZIP(), []int{0, 1, 2}
}

func (x *Distribution_BucketOptions_Explicit) GetBounds() []float64 {
	if x != nil {
		return x.Bounds
	}
	return nil
}

var File_metrics_distribution_proto protoreflect.FileDescriptor

const file_metrics_distribution_proto_rawDesc = "" +
	"\n" +
	"\x1ametrics/distribution.proto\x12\ametrics\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa5\b\n" +
	"\fDistribution\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\x12\x12\n" +
	"\x04mean\x18\x02 \x01(\x01R\x04mean\x127\n" +
	"\x18sum_of_squared_deviation\x18\x03 \x01(\x01R\x15sumOfSquaredDeviation\x121\n" +
	"\x05range\x18\x04 \x01(\v2\x1b.metrics.Distribution.RangeR\x05range\x12J\n" +
	"\x0ebucket_options\x18\x06 \x01(\v2#.metrics.Distribution.BucketOptionsR\rbucketOptions\x12#\n" +
	"\rbucket_counts\x18\a \x03(\x03R\fbucketCounts\x12<\n" +
	"\texemplars\x18\n" +
	" \x03(\v2\x1e.metrics.Distribution.ExemplarR\texemplars\x1a+\n" +
	"\x05Range\x12\x10\n" +
	"\x03min\x18\x01 \x01(\x01R\x03min\x12\x10\n" +
	"\x03max\x18\x02 \x01(\x01R\x03max\x1a\xb0\x04\n" +
	"\rBucketOptions\x12S\n" +
	"\x0elinear_buckets\x18\x01 \x01(\v2*.metrics.Distribution.BucketOptions.LinearH\x00R\rlinearBuckets\x12b\n" +
	"\x13exponential_buckets\x18\x02 \x01(\v2/.metrics.Distribution.BucketOptions.ExponentialH\x00R\x12exponentialBuckets\x12Y\n" +
	"\x10explicit_buckets\x18\x03 \x01(\v2,.metrics.Distribution.BucketOptions.ExplicitH\x00R\x0fexplicitBuckets\x1ad\n" +
	"\x06Linear\x12,\n" +
	"\x12num_finite_buckets\x18\x01 \x01(\x05R\x10numFiniteBuckets\x12\x14\n" +
	"\x05width\x18\x02 \x01(\x01R\x05width\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x01R\x06offset\x1av\n" +
	"\vExponential\x12,\n" +
	"\x12num_finite_buckets\x18\x01 \x01(\x05R\x10numFiniteBuckets\x12#\n" +
	"\rgrowth_factor\x18\x02 \x01(\x01R\fgrowthFactor\x12\x14\n" +
	"\x05scale\x18\x03 \x01(\x01R\x05scale\x1a\"\n" +
	"\bExplicit\x12\x16\n" +
	"\x06bounds\x18\x01 \x03(\x01R\x06boundsB\t\n" +
	"\aoptions\x1ap\n" +
	"\bExemplar\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x14\n" +
	"\x05label\x18\x03 \x01(\tR\x05labelB.Z,github.com/accretional/grpc-server-config/pbb\x06proto3"

var (
	file_metrics_distribution_proto_rawDescOnce sync.Once
	file_metrics_distribution_proto_rawDescData []byte
)

func file_metrics_distribution_proto_rawDescGZIP() []byte {
	file_metrics_distribution_proto_rawDescOnce.Do(func() {
		file_metrics_distribution_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_distribution_proto_rawDesc), len(file_metrics_distribution_proto_rawDesc)))
	})
	return file_metrics_distribution_proto_rawDescData
}

var file_metrics_distribution_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_metrics_distribution_proto_goTypes = []any{
	(*Distribution)(nil),                           // 0: metrics.Distribution
	(*Distribution_Range)(nil),                     // 1: metrics.Distribution.Range
	(*Distribution_BucketOptions)(nil),             // 2: metrics.Distribution.BucketOptions
	(*Distribution_Exemplar)(nil),                  // 3: metrics.Distribution.Exemplar
	(*Distribution_BucketOptions_Linear)(nil),      // 4: metrics.Distribution.BucketOptions.Linear
	(*Distribution_BucketOptions_Exponential)(nil), // 5: metrics.Distribution.BucketOptions.Exponential
	(*Distribution_BucketOptions_Explicit)(nil),    // 6: metrics.Distribution.BucketOptions.Explicit
	(*timestamppb.Timestamp)(nil),                  // 7: google.protobuf.Timestamp
}
var file_metrics_distribution_proto_depIdxs = []int32{
	1, // 0: metrics.Distribution.range:type_name -> metrics.Distribution.Range
	2, // 1: metrics.Distribution.bucket_options:type_name -> metrics.Distribution.BucketOptions
	3, // 2: metrics.Distribution.exemplars:type_name -> metrics.Distribution.Exemplar
	4, // 3: metrics.Distribution.BucketOptions.linear_buckets:type_name -> metrics.Distribution.BucketOptions.Linear
	5, // 4: metrics.Distribution.BucketOptions.exponential_buckets:type_name -> metrics.Distribution.BucketOptions.Exponential
	6, // 5: metrics.Distribution.BucketOptions.explicit_buckets:type_name -> metrics.Distribution.BucketOptions.Explicit
	7, // 6: metrics.Distribution.Exemplar.timestamp:type_name -> google.protobuf.Timestamp
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_metrics_distribution_proto_init() }
func file_metrics_distribution_proto_init() {
	if File_metrics_distribution_proto != nil {
		return
	}
	file_metrics_distribution_proto_msgTypes[2].OneofWrappers = []any{
		(*Distribution_BucketOptions_LinearBuckets)(nil),
		(*Distribution_BucketOptions_ExponentialBuckets)(nil),
		(*Distribution_BucketOptions_ExplicitBuckets)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_distribution_proto_rawDesc), len(file_metrics_distribution_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_distribution_proto_goTypes,
		DependencyIndexes: file_metrics_distribution_proto_depIdxs,
		MessageInfos:      file_metrics_distribution_proto_msgTypes,
	}.Build()
	File_metrics_distribution_proto = out.File
	file_metrics_distribution_proto_goTypes = nil
	file_metrics_distribution_proto_depIdxs = nil
}
