// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: metrics/metric.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MetricKind describes how a metric's value accumulates over time.
// Adapted from google.api.MetricDescriptor.MetricKind.
type MetricKind int32

const (
	MetricKind_METRIC_KIND_UNSPECIFIED MetricKind = 0
	// Instantaneous measurement. Each point is independent.
	MetricKind_GAUGE MetricKind = 1
	// Change in a value during a time window [start, start+duration).
	// Consecutive windows should be contiguous and non-overlapping.
	MetricKind_DELTA MetricKind = 2
	// Total accumulated since a fixed epoch. Resets (e.g. process restart)
	// produce a new CumulativeTimeSeries with a fresh epoch_start rather than
	// mutating the existing series.
	MetricKind_CUMULATIVE MetricKind = 3
)

// Enum value maps for MetricKind.
var (
	MetricKind_name = map[int32]string{
		0: "METRIC_KIND_UNSPECIFIED",
		1: "GAUGE",
		2: "DELTA",
		3: "CUMULATIVE",
	}
	MetricKind_value = map[string]int32{
		"METRIC_KIND_UNSPECIFIED": 0,
		"GAUGE":                   1,
		"DELTA":                   2,
		"CUMULATIVE":              3,
	}
)

func (x MetricKind) Enum() *MetricKind {
	p := new(MetricKind)
	*p = x
	return p
}

func (x MetricKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricKind) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_metric_proto_enumTypes[0].Descriptor()
}

func (MetricKind) Type() protoreflect.EnumType {
	return &file_metrics_metric_proto_enumTypes[0]
}

func (x MetricKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricKind.Descriptor instead.
func (MetricKind) EnumDescriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{0}
}

// ValueType describes the data type of individual metric points.
// Adapted from google.api.MetricDescriptor.ValueType.
// Note: BOOL and STRING are only valid for GAUGE metrics. DELTA and CUMULATIVE
// metrics must use NumericValue (INT64, DOUBLE, or DISTRIBUTION).
type ValueType int32

const (
	ValueType_VALUE_TYPE_UNSPECIFIED ValueType = 0
	ValueType_BOOL                   ValueType = 1 // GAUGE only
	ValueType_INT64                  ValueType = 2
	ValueType_DOUBLE                 ValueType = 3
	ValueType_STRING                 ValueType = 4 // GAUGE only
	ValueType_DISTRIBUTION           ValueType = 5
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "VALUE_TYPE_UNSPECIFIED",
		1: "BOOL",
		2: "INT64",
		3: "DOUBLE",
		4: "STRING",
		5: "DISTRIBUTION",
	}
	ValueType_value = map[string]int32{
		"VALUE_TYPE_UNSPECIFIED": 0,
		"BOOL":                   1,
		"INT64":                  2,
		"DOUBLE":                 3,
		"STRING":                 4,
		"DISTRIBUTION":           5,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_metric_proto_enumTypes[1].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_metrics_metric_proto_enumTypes[1]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{1}
}

type LabelDescriptor_ValueType int32

const (
	LabelDescriptor_STRING LabelDescriptor_ValueType = 0
	LabelDescriptor_BOOL   LabelDescriptor_ValueType = 1
	LabelDescriptor_INT64  LabelDescriptor_ValueType = 2
)

// Enum value maps for LabelDescriptor_ValueType.
var (
	LabelDescriptor_ValueType_name = map[int32]string{
		0: "STRING",
		1: "BOOL",
		2: "INT64",
	}
	LabelDescriptor_ValueType_value = map[string]int32{
		"STRING": 0,
		"BOOL":   1,
		"INT64":  2,
	}
)

func (x LabelDescriptor_ValueType) Enum() *LabelDescriptor_ValueType {
	p := new(LabelDescriptor_ValueType)
	*p = x
	return p
}

func (x LabelDescriptor_ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelDescriptor_ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_metrics_metric_proto_enumTypes[2].Descriptor()
}

func (LabelDescriptor_ValueType) Type() protoreflect.EnumType {
	return &file_metrics_metric_proto_enumTypes[2]
}

func (x LabelDescriptor_ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelDescriptor_ValueType.Descriptor instead.
func (LabelDescriptor_ValueType) EnumDescriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{0, 0}
}

// LabelDescriptor describes a single label key and the type of its values.
// Adapted from google.api.LabelDescriptor.
type LabelDescriptor struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Key           string                    `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	ValueType     LabelDescriptor_ValueType `protobuf:"varint,2,opt,name=value_type,json=valueType,proto3,enum=metrics.LabelDescriptor_ValueType" json:"value_type,omitempty"`
	Description   string                    `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelDescriptor) Reset() {
	*x = LabelDescriptor{}
	mi := &file_metrics_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelDescriptor) ProtoMessage() {}

func (x *LabelDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelDescriptor.ProtoReflect.Descriptor instead.
func (*LabelDescriptor) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{0}
}

func (x *LabelDescriptor) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelDescriptor) GetValueType() LabelDescriptor_ValueType {
	if x != nil {
		return x.ValueType
	}
	return LabelDescriptor_STRING
}

func (x *LabelDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// MetricDescriptor defines a metric type and the schema for its time series.
// Adapted from google.api.MetricDescriptor; GCP-specific fields (launch_stage,
// monitored_resource_types, MetricDescriptorMetadata) are omitted.
type MetricDescriptor struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Hierarchical type name, e.g. "server/http/request_count".
	// Matches the type field on Metric instances of this descriptor.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Concise human-readable name, e.g. "HTTP request count".
	DisplayName string `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Full description for documentation.
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	// Label keys valid for this metric type. All keys must appear in
	// Metric.labels when a time series is created.
	Labels     []*LabelDescriptor `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty"`
	MetricKind MetricKind         `protobuf:"varint,5,opt,name=metric_kind,json=metricKind,proto3,enum=metrics.MetricKind" json:"metric_kind,omitempty"`
	ValueType  ValueType          `protobuf:"varint,6,opt,name=value_type,json=valueType,proto3,enum=metrics.ValueType" json:"value_type,omitempty"`
	// Unit string following UCUM, e.g. "By", "s", "1/s", "{request}".
	// Only meaningful for INT64, DOUBLE, and DISTRIBUTION value types.
	Unit          string `protobuf:"bytes,7,opt,name=unit,proto3" json:"unit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetricDescriptor) Reset() {
	*x = MetricDescriptor{}
	mi := &file_metrics_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricDescriptor) ProtoMessage() {}

func (x *MetricDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricDescriptor.ProtoReflect.Descriptor instead.
func (*MetricDescriptor) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{1}
}

func (x *MetricDescriptor) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MetricDescriptor) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *MetricDescriptor) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MetricDescriptor) GetLabels() []*LabelDescriptor {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *MetricDescriptor) GetMetricKind() MetricKind {
	if x != nil {
		return x.MetricKind
	}
	return MetricKind_METRIC_KIND_UNSPECIFIED
}

func (x *MetricDescriptor) GetValueType() ValueType {
	if x != nil {
		return x.ValueType
	}
	return ValueType_VALUE_TYPE_UNSPECIFIED
}

func (x *MetricDescriptor) GetUnit() string {
	if x != nil {
		return x.Unit
	}
	return ""
}

// Metric identifies a specific time series: a metric type paired with a
// complete set of label values.
// Adapted from google.api.Metric.
type Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Matches MetricDescriptor.type, e.g. "server/http/request_count".
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Label key-value pairs. Every key declared in MetricDescriptor.labels
	// must have a value here.
	Labels        map[string]string `protobuf:"bytes,2,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metric) Reset() {
	*x = Metric{}
	mi := &file_metrics_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metric) ProtoMessage() {}

func (x *Metric) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metric.ProtoReflect.Descriptor instead.
func (*Metric) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{2}
}

func (x *Metric) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Metric) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

// TypedValue holds a single data point value for any MetricKind.
// All five variants are valid for GAUGE. DELTA and CUMULATIVE must use
// NumericValue, which excludes BOOL and STRING.
type TypedValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*TypedValue_BoolValue
	//	*TypedValue_Int64Value
	//	*TypedValue_DoubleValue
	//	*TypedValue_StringValue
	//	*TypedValue_DistributionValue
	Value         isTypedValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypedValue) Reset() {
	*x = TypedValue{}
	mi := &file_metrics_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypedValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypedValue) ProtoMessage() {}

func (x *TypedValue) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypedValue.ProtoReflect.Descriptor instead.
func (*TypedValue) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{3}
}

func (x *TypedValue) GetValue() isTypedValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *TypedValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *TypedValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *TypedValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *TypedValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *TypedValue) GetDistributionValue() *Distribution {
	if x != nil {
		if x, ok := x.Value.(*TypedValue_DistributionValue); ok {
			return x.DistributionValue
		}
	}
	return nil
}

type isTypedValue_Value interface {
	isTypedValue_Value()
}

type TypedValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,1,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type TypedValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,2,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type TypedValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type TypedValue_StringValue struct {
	StringValue string `protobuf:"bytes,4,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type TypedValue_DistributionValue struct {
	DistributionValue *Distribution `protobuf:"bytes,5,opt,name=distribution_value,json=distributionValue,proto3,oneof"`
}

func (*TypedValue_BoolValue) isTypedValue_Value() {}

func (*TypedValue_Int64Value) isTypedValue_Value() {}

func (*TypedValue_DoubleValue) isTypedValue_Value() {}

func (*TypedValue_StringValue) isTypedValue_Value() {}

func (*TypedValue_DistributionValue) isTypedValue_Value() {}

// NumericValue is the value type for DELTA and CUMULATIVE metrics.
// BOOL and STRING are excluded: you cannot meaningfully delta a boolean or
// accumulate a string.
type NumericValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*NumericValue_Int64Value
	//	*NumericValue_DoubleValue
	//	*NumericValue_DistributionValue
	Value         isNumericValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericValue) Reset() {
	*x = NumericValue{}
	mi := &file_metrics_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericValue) ProtoMessage() {}

func (x *NumericValue) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericValue.ProtoReflect.Descriptor instead.
func (*NumericValue) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{4}
}

func (x *NumericValue) GetValue() isNumericValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *NumericValue) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*NumericValue_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *NumericValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*NumericValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *NumericValue) GetDistributionValue() *Distribution {
	if x != nil {
		if x, ok := x.Value.(*NumericValue_DistributionValue); ok {
			return x.DistributionValue
		}
	}
	return nil
}

type isNumericValue_Value interface {
	isNumericValue_Value()
}

type NumericValue_Int64Value struct {
	Int64Value int64 `protobuf:"varint,1,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type NumericValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type NumericValue_DistributionValue struct {
	DistributionValue *Distribution `protobuf:"bytes,3,opt,name=distribution_value,json=distributionValue,proto3,oneof"`
}

func (*NumericValue_Int64Value) isNumericValue_Value() {}

func (*NumericValue_DoubleValue) isNumericValue_Value() {}

func (*NumericValue_DistributionValue) isNumericValue_Value() {}

// GaugePoint is an instantaneous measurement at a single moment in time.
type GaugePoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	At            *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=at,proto3" json:"at,omitempty"`
	Value         *TypedValue            `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GaugePoint) Reset() {
	*x = GaugePoint{}
	mi := &file_metrics_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaugePoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaugePoint) ProtoMessage() {}

func (x *GaugePoint) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaugePoint.ProtoReflect.Descriptor instead.
func (*GaugePoint) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{5}
}

func (x *GaugePoint) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *GaugePoint) GetValue() *TypedValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// NumericPoint is a (duration, value) pair used by both DeltaTimeSeries and
// CumulativeTimeSeries. The semantic meaning of duration depends on the
// containing series type:
//
//	DeltaTimeSeries:      width of the measurement window
//	CumulativeTimeSeries: time elapsed since the previous point's end (or
//	                      since epoch_start for the first point)
//
// In both cases the per-series anchor (start / epoch_start) plus the
// cumulative sum of durations gives the absolute time of each point boundary,
// and structural ordering guarantees come from the series, not from this type.
//
// Constraint (enforced by consumers, unavoidable in proto3):
//
//	duration > 0
type NumericPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Duration      *durationpb.Duration   `protobuf:"bytes,1,opt,name=duration,proto3" json:"duration,omitempty"`
	Value         *NumericValue          `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NumericPoint) Reset() {
	*x = NumericPoint{}
	mi := &file_metrics_metric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NumericPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NumericPoint) ProtoMessage() {}

func (x *NumericPoint) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NumericPoint.ProtoReflect.Descriptor instead.
func (*NumericPoint) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{6}
}

func (x *NumericPoint) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

func (x *NumericPoint) GetValue() *NumericValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// GaugeTimeSeries is a sequence of instantaneous measurements.
// Points need not be evenly spaced; gaps are permitted.
type GaugeTimeSeries struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metric        *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Resource      *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	Points        []*GaugePoint          `protobuf:"bytes,3,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GaugeTimeSeries) Reset() {
	*x = GaugeTimeSeries{}
	mi := &file_metrics_metric_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GaugeTimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GaugeTimeSeries) ProtoMessage() {}

func (x *GaugeTimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GaugeTimeSeries.ProtoReflect.Descriptor instead.
func (*GaugeTimeSeries) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{7}
}

func (x *GaugeTimeSeries) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *GaugeTimeSeries) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *GaugeTimeSeries) GetPoints() []*GaugePoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// DeltaTimeSeries is a sequence of contiguous, non-overlapping delta windows.
// The start of window[i] is: start + sum(point[0..i-1].duration)
// The end   of window[i] is: start + sum(point[0..i].duration)
type DeltaTimeSeries struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metric   *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Resource *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Start of the first window. All subsequent windows follow contiguously.
	Start         *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	Points        []*NumericPoint        `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeltaTimeSeries) Reset() {
	*x = DeltaTimeSeries{}
	mi := &file_metrics_metric_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeltaTimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeltaTimeSeries) ProtoMessage() {}

func (x *DeltaTimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeltaTimeSeries.ProtoReflect.Descriptor instead.
func (*DeltaTimeSeries) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{8}
}

func (x *DeltaTimeSeries) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *DeltaTimeSeries) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DeltaTimeSeries) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *DeltaTimeSeries) GetPoints() []*NumericPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

// CumulativeTimeSeries records accumulated totals since a fixed epoch.
//
// A counter reset (process restart, rollover, etc.) produces a NEW
// CumulativeTimeSeries with a fresh epoch_start — not a mutation of this
// series. This makes resets structurally visible rather than a special case
// requiring out-of-band detection.
//
// The absolute end time of point[i] is: epoch_start + sum(point[0..i].duration)
type CumulativeTimeSeries struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Metric   *Metric                `protobuf:"bytes,1,opt,name=metric,proto3" json:"metric,omitempty"`
	Resource *Resource              `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	// Fixed start of the accumulation epoch for the lifetime of this series.
	EpochStart    *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=epoch_start,json=epochStart,proto3" json:"epoch_start,omitempty"`
	Points        []*NumericPoint        `protobuf:"bytes,4,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CumulativeTimeSeries) Reset() {
	*x = CumulativeTimeSeries{}
	mi := &file_metrics_metric_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CumulativeTimeSeries) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CumulativeTimeSeries) ProtoMessage() {}

func (x *CumulativeTimeSeries) ProtoReflect() protoreflect.Message {
	mi := &file_metrics_metric_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CumulativeTimeSeries.ProtoReflect.Descriptor instead.
func (*CumulativeTimeSeries) Descriptor() ([]byte, []int) {
	return file_metrics_metric_proto_rawDescGZIP(), []int{9}
}

func (x *CumulativeTimeSeries) GetMetric() *Metric {
	if x != nil {
		return x.Metric
	}
	return nil
}

func (x *CumulativeTimeSeries) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *CumulativeTimeSeries) GetEpochStart() *timestamppb.Timestamp {
	if x != nil {
		return x.EpochStart
	}
	return nil
}

func (x *CumulativeTimeSeries) GetPoints() []*NumericPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

var File_metrics_metric_proto protoreflect.FileDescriptor

const file_metrics_metric_proto_rawDesc = "" +
	"\n" +
	"\x14metrics/metric.proto\x12\ametrics\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1ametrics/distribution.proto\x1a\x17resource/resource.proto\"\xb6\x01\n" +
	"\x0fLabelDescriptor\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12A\n" +
	"\n" +
	"value_type\x18\x02 \x01(\x0e2\".metrics.LabelDescriptor.ValueTypeR\tvalueType\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\",\n" +
	"\tValueType\x12\n" +
	"\n" +
	"\x06STRING\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\t\n" +
	"\x05INT64\x10\x02\"\x9a\x02\n" +
	"\x10MetricDescriptor\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x120\n" +
	"\x06labels\x18\x04 \x03(\v2\x18.metrics.LabelDescriptorR\x06labels\x124\n" +
	"\vmetric_kind\x18\x05 \x01(\x0e2\x13.metrics.MetricKindR\n" +
	"metricKind\x121\n" +
	"\n" +
	"value_type\x18\x06 \x01(\x0e2\x12.metrics.ValueTypeR\tvalueType\x12\x12\n" +
	"\x04unit\x18\a \x01(\tR\x04unit\"\x8c\x01\n" +
	"\x06Metric\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x123\n" +
	"\x06labels\x18\x02 \x03(\v2\x1b.metrics.Metric.LabelsEntryR\x06labels\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x01\n" +
	"\n" +
	"TypedValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x01 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vint64_value\x18\x02 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12#\n" +
	"\fstring_value\x18\x04 \x01(\tH\x00R\vstringValue\x12F\n" +
	"\x12distribution_value\x18\x05 \x01(\v2\x15.metrics.DistributionH\x00R\x11distributionValueB\a\n" +
	"\x05value\"\xa7\x01\n" +
	"\fNumericValue\x12!\n" +
	"\vint64_value\x18\x01 \x01(\x03H\x00R\n" +
	"int64Value\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12F\n" +
	"\x12distribution_value\x18\x03 \x01(\v2\x15.metrics.DistributionH\x00R\x11distributionValueB\a\n" +
	"\x05value\"c\n" +
	"\n" +
	"GaugePoint\x12*\n" +
	"\x02at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\x02at\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.metrics.TypedValueR\x05value\"r\n" +
	"\fNumericPoint\x125\n" +
	"\bduration\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12+\n" +
	"\x05value\x18\x02 \x01(\v2\x15.metrics.NumericValueR\x05value\"\x97\x01\n" +
	"\x0fGaugeTimeSeries\x12'\n" +
	"\x06metric\x18\x01 \x01(\v2\x0f.metrics.MetricR\x06metric\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.resource.ResourceR\bresource\x12+\n" +
	"\x06points\x18\x03 \x03(\v2\x13.metrics.GaugePointR\x06points\"\xcb\x01\n" +
	"\x0fDeltaTimeSeries\x12'\n" +
	"\x06metric\x18\x01 \x01(\v2\x0f.metrics.MetricR\x06metric\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.resource.ResourceR\bresource\x120\n" +
	"\x05start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x05start\x12-\n" +
	"\x06points\x18\x04 \x03(\v2\x15.metrics.NumericPointR\x06points\"\xdb\x01\n" +
	"\x14CumulativeTimeSeries\x12'\n" +
	"\x06metric\x18\x01 \x01(\v2\x0f.metrics.MetricR\x06metric\x12.\n" +
	"\bresource\x18\x02 \x01(\v2\x12.resource.ResourceR\bresource\x12;\n" +
	"\vepoch_start\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"epochStart\x12-\n" +
	"\x06points\x18\x04 \x03(\v2\x15.metrics.NumericPointR\x06points*O\n" +
	"\n" +
	"MetricKind\x12\x1b\n" +
	"\x17METRIC_KIND_UNSPECIFIED\x10\x00\x12\t\n" +
	"\x05GAUGE\x10\x01\x12\t\n" +
	"\x05DELTA\x10\x02\x12\x0e\n" +
	"\n" +
	"CUMULATIVE\x10\x03*f\n" +
	"\tValueType\x12\x1a\n" +
	"\x16VALUE_TYPE_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04BOOL\x10\x01\x12\t\n" +
	"\x05INT64\x10\x02\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x03\x12\n" +
	"\n" +
	"\x06STRING\x10\x04\x12\x10\n" +
	"\fDISTRIBUTION\x10\x05B.Z,github.com/accretional/grpc-server-config/pbb\x06proto3"

var (
	file_metrics_metric_proto_rawDescOnce sync.Once
	file_metrics_metric_proto_rawDescData []byte
)

func file_metrics_metric_proto_rawDescGZIP() []byte {
	file_metrics_metric_proto_rawDescOnce.Do(func() {
		file_metrics_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_metrics_metric_proto_rawDesc), len(file_metrics_metric_proto_rawDesc)))
	})
	return file_metrics_metric_proto_rawDescData
}

var file_metrics_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_metrics_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_metrics_metric_proto_goTypes = []any{
	(MetricKind)(0),                // 0: metrics.MetricKind
	(ValueType)(0),                 // 1: metrics.ValueType
	(LabelDescriptor_ValueType)(0), // 2: metrics.LabelDescriptor.ValueType
	(*LabelDescriptor)(nil),        // 3: metrics.LabelDescriptor
	(*MetricDescriptor)(nil),       // 4: metrics.MetricDescriptor
	(*Metric)(nil),                 // 5: metrics.Metric
	(*TypedValue)(nil),             // 6: metrics.TypedValue
	(*NumericValue)(nil),           // 7: metrics.NumericValue
	(*GaugePoint)(nil),             // 8: metrics.GaugePoint
	(*NumericPoint)(nil),           // 9: metrics.NumericPoint
	(*GaugeTimeSeries)(nil),        // 10: metrics.GaugeTimeSeries
	(*DeltaTimeSeries)(nil),        // 11: metrics.DeltaTimeSeries
	(*CumulativeTimeSeries)(nil),   // 12: metrics.CumulativeTimeSeries
	nil,                            // 13: metrics.Metric.LabelsEntry
	(*Distribution)(nil),           // 14: metrics.Distribution
	(*timestamppb.Timestamp)(nil),  // 15: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),    // 16: google.protobuf.Duration
	(*Resource)(nil),               // 17: resource.Resource
}
var file_metrics_metric_proto_depIdxs = []int32{
	2,  // 0: metrics.LabelDescriptor.value_type:type_name -> metrics.LabelDescriptor.ValueType
	3,  // 1: metrics.MetricDescriptor.labels:type_name -> metrics.LabelDescriptor
	0,  // 2: metrics.MetricDescriptor.metric_kind:type_name -> metrics.MetricKind
	1,  // 3: metrics.MetricDescriptor.value_type:type_name -> metrics.ValueType
	13, // 4: metrics.Metric.labels:type_name -> metrics.Metric.LabelsEntry
	14, // 5: metrics.TypedValue.distribution_value:type_name -> metrics.Distribution
	14, // 6: metrics.NumericValue.distribution_value:type_name -> metrics.Distribution
	15, // 7: metrics.GaugePoint.at:type_name -> google.protobuf.Timestamp
	6,  // 8: metrics.GaugePoint.value:type_name -> metrics.TypedValue
	16, // 9: metrics.NumericPoint.duration:type_name -> google.protobuf.Duration
	7,  // 10: metrics.NumericPoint.value:type_name -> metrics.NumericValue
	5,  // 11: metrics.GaugeTimeSeries.metric:type_name -> metrics.Metric
	17, // 12: metrics.GaugeTimeSeries.resource:type_name -> resource.Resource
	8,  // 13: metrics.GaugeTimeSeries.points:type_name -> metrics.GaugePoint
	5,  // 14: metrics.DeltaTimeSeries.metric:type_name -> metrics.Metric
	17, // 15: metrics.DeltaTimeSeries.resource:type_name -> resource.Resource
	15, // 16: metrics.DeltaTimeSeries.start:type_name -> google.protobuf.Timestamp
	9,  // 17: metrics.DeltaTimeSeries.points:type_name -> metrics.NumericPoint
	5,  // 18: metrics.CumulativeTimeSeries.metric:type_name -> metrics.Metric
	17, // 19: metrics.CumulativeTimeSeries.resource:type_name -> resource.Resource
	15, // 20: metrics.CumulativeTimeSeries.epoch_start:type_name -> google.protobuf.Timestamp
	9,  // 21: metrics.CumulativeTimeSeries.points:type_name -> metrics.NumericPoint
	22, // [22:22] is the sub-list for method output_type
	22, // [22:22] is the sub-list for method input_type
	22, // [22:22] is the sub-list for extension type_name
	22, // [22:22] is the sub-list for extension extendee
	0,  // [0:22] is the sub-list for field type_name
}

func init() { file_metrics_metric_proto_init() }
func file_metrics_metric_proto_init() {
	if File_metrics_metric_proto != nil {
		return
	}
	file_metrics_distribution_proto_init()
	file_resource_resource_proto_init()
	file_metrics_metric_proto_msgTypes[3].OneofWrappers = []any{
		(*TypedValue_BoolValue)(nil),
		(*TypedValue_Int64Value)(nil),
		(*TypedValue_DoubleValue)(nil),
		(*TypedValue_StringValue)(nil),
		(*TypedValue_DistributionValue)(nil),
	}
	file_metrics_metric_proto_msgTypes[4].OneofWrappers = []any{
		(*NumericValue_Int64Value)(nil),
		(*NumericValue_DoubleValue)(nil),
		(*NumericValue_DistributionValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_metrics_metric_proto_rawDesc), len(file_metrics_metric_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_metrics_metric_proto_goTypes,
		DependencyIndexes: file_metrics_metric_proto_depIdxs,
		EnumInfos:         file_metrics_metric_proto_enumTypes,
		MessageInfos:      file_metrics_metric_proto_msgTypes,
	}.Build()
	File_metrics_metric_proto = out.File
	file_metrics_metric_proto_goTypes = nil
	file_metrics_metric_proto_depIdxs = nil
}
